# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Errors
      autoload :APIError, "cloudinary_account_provisioning/models/errors/apierror.rb"
      autoload :ErrorResponse, "cloudinary_account_provisioning/models/errors/errorresponse.rb"
      autoload :PermissionsErrorResponse, "cloudinary_account_provisioning/models/errors/permissionserrorresponse.rb"
    end
  end
end
