# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared
      autoload :AccessKey, "cloudinary_account_provisioning/models/shared/accesskey.rb"
      autoload :AccessKeyRequest, "cloudinary_account_provisioning/models/shared/accesskeyrequest.rb"
      autoload :AccessKeyUpdateRequest, "cloudinary_account_provisioning/models/shared/accesskeyupdaterequest.rb"
      autoload :AccessKeysResponse, "cloudinary_account_provisioning/models/shared/accesskeysresponse.rb"
      autoload :ApiAccessKey, "cloudinary_account_provisioning/models/shared/apiaccesskey.rb"
      autoload :BillingUsageResponse, "cloudinary_account_provisioning/models/shared/billingusageresponse.rb"
      autoload(
        :BillingUsageResponseBreakdown,
        "cloudinary_account_provisioning/models/shared/billingusageresponse_breakdown.rb"
      )
      autoload :CedarError, "cloudinary_account_provisioning/models/shared/cedarerror.rb"
      autoload :CedarSchemaResponse, "cloudinary_account_provisioning/models/shared/cedarschemaresponse.rb"
      autoload :CloudAssetTypeBreakdown, "cloudinary_account_provisioning/models/shared/cloudassettypebreakdown.rb"
      autoload :CreateRole, "cloudinary_account_provisioning/models/shared/createrole.rb"
      autoload :CustomPoliciesResponse, "cloudinary_account_provisioning/models/shared/custompoliciesresponse.rb"
      autoload :CustomPolicy, "cloudinary_account_provisioning/models/shared/custompolicy.rb"
      autoload :CustomPolicyResponse, "cloudinary_account_provisioning/models/shared/custompolicyresponse.rb"
      autoload :CustomPolicyResponseData, "cloudinary_account_provisioning/models/shared/custompolicyresponsedata.rb"
      autoload :EffectivePoliciesResponse, "cloudinary_account_provisioning/models/shared/effectivepoliciesresponse.rb"
      autoload :EffectivePolicy, "cloudinary_account_provisioning/models/shared/effectivepolicy.rb"
      autoload :EffectiveRole, "cloudinary_account_provisioning/models/shared/effectiverole.rb"
      autoload :InspectRequest, "cloudinary_account_provisioning/models/shared/inspectrequest.rb"
      autoload(
        :InspectRequestPolicyParameters,
        "cloudinary_account_provisioning/models/shared/inspectrequest_policy_parameters.rb"
      )
      autoload :ManagementTypeEnum, "cloudinary_account_provisioning/models/shared/managementtypeenum.rb"
      autoload :OperationEnum, "cloudinary_account_provisioning/models/shared/operationenum.rb"
      autoload :PermissionTypeEnum, "cloudinary_account_provisioning/models/shared/permissiontypeenum.rb"
      autoload :PermissionsError, "cloudinary_account_provisioning/models/shared/permissionserror.rb"
      autoload :Principal, "cloudinary_account_provisioning/models/shared/principal.rb"
      autoload :PrincipalResponseData, "cloudinary_account_provisioning/models/shared/principalresponsedata.rb"
      autoload(
        :PrincipalResponseDataPolicyParameters,
        "cloudinary_account_provisioning/models/shared/principalresponsedata_policy_parameters.rb"
      )
      autoload :PrincipalRole, "cloudinary_account_provisioning/models/shared/principalrole.rb"
      autoload :PrincipalRolesData, "cloudinary_account_provisioning/models/shared/principalrolesdata.rb"
      autoload :PrincipalRolesInspectData, "cloudinary_account_provisioning/models/shared/principalrolesinspectdata.rb"
      autoload(
        :PrincipalRolesInspectResponse,
        "cloudinary_account_provisioning/models/shared/principalrolesinspectresponse.rb"
      )
      autoload(
        :PrincipalRolesInspectResponseData,
        "cloudinary_account_provisioning/models/shared/principalrolesinspectresponse_data.rb"
      )
      autoload :PrincipalRolesResponse, "cloudinary_account_provisioning/models/shared/principalrolesresponse.rb"
      autoload :PrincipalTypeEnum, "cloudinary_account_provisioning/models/shared/principaltypeenum.rb"
      autoload :PrincipalsResponse, "cloudinary_account_provisioning/models/shared/principalsresponse.rb"
      autoload :ProductEnvironment, "cloudinary_account_provisioning/models/shared/productenvironment.rb"
      autoload :ProductEnvironmentRequest, "cloudinary_account_provisioning/models/shared/productenvironmentrequest.rb"
      autoload(
        :ProductEnvironmentUpdateRequest,
        "cloudinary_account_provisioning/models/shared/productenvironmentupdaterequest.rb"
      )
      autoload(
        :ProductEnvironmentUpdateRequestCustomAttributes,
        "cloudinary_account_provisioning/models/shared/productenvironmentupdaterequest_custom_attributes.rb"
      )
      autoload(
        :ProductEnvironmentsResponse,
        "cloudinary_account_provisioning/models/shared/productenvironmentsresponse.rb"
      )
      autoload :Role, "cloudinary_account_provisioning/models/shared/role.rb"
      autoload :RoleResponse, "cloudinary_account_provisioning/models/shared/roleresponse.rb"
      autoload :RoleResponseData, "cloudinary_account_provisioning/models/shared/roleresponsedata.rb"
      autoload :RoleResponseData1, "cloudinary_account_provisioning/models/shared/roleresponse_data1.rb"
      autoload :RoleToManage, "cloudinary_account_provisioning/models/shared/roletomanage.rb"
      autoload(
        :RoleToManagePolicyParameters,
        "cloudinary_account_provisioning/models/shared/roletomanage_policy_parameters.rb"
      )
      autoload :RolesResponse, "cloudinary_account_provisioning/models/shared/rolesresponse.rb"
      autoload :ScopeTypeEnum, "cloudinary_account_provisioning/models/shared/scopetypeenum.rb"
      autoload :Security, "cloudinary_account_provisioning/models/shared/security.rb"
      autoload :SubAccountSummary, "cloudinary_account_provisioning/models/shared/subaccountsummary.rb"
      autoload :SuccessResponse, "cloudinary_account_provisioning/models/shared/successresponse.rb"
      autoload :SystemPoliciesResponse, "cloudinary_account_provisioning/models/shared/systempoliciesresponse.rb"
      autoload :SystemPolicyResponseData, "cloudinary_account_provisioning/models/shared/systempolicyresponsedata.rb"
      autoload(
        :SystemRolesAndPoliciesCatalogResponse,
        "cloudinary_account_provisioning/models/shared/systemrolesandpoliciescatalogresponse.rb"
      )
      autoload :UpdateCustomPolicy, "cloudinary_account_provisioning/models/shared/updatecustompolicy.rb"
      autoload(
        :UpdatePrincipalRolesRequest,
        "cloudinary_account_provisioning/models/shared/updateprincipalrolesrequest.rb"
      )
      autoload :UpdateRolePrincipal, "cloudinary_account_provisioning/models/shared/updateroleprincipal.rb"
      autoload(
        :UpdateRolePrincipalPolicyParameters,
        "cloudinary_account_provisioning/models/shared/updateroleprincipal_policy_parameters.rb"
      )
      autoload(
        :UpdateRolePrincipalsRequest,
        "cloudinary_account_provisioning/models/shared/updateroleprincipalsrequest.rb"
      )
      autoload :User, "cloudinary_account_provisioning/models/shared/user.rb"
      autoload :UserGroup, "cloudinary_account_provisioning/models/shared/usergroup.rb"
      autoload :UserGroupRequest, "cloudinary_account_provisioning/models/shared/usergrouprequest.rb"
      autoload :UserGroupSummary, "cloudinary_account_provisioning/models/shared/usergroupsummary.rb"
      autoload :UserGroupUser, "cloudinary_account_provisioning/models/shared/usergroupuser.rb"
      autoload :UserGroupUsersResponse, "cloudinary_account_provisioning/models/shared/usergroupusersresponse.rb"
      autoload :UserGroupsListResponse, "cloudinary_account_provisioning/models/shared/usergroupslistresponse.rb"
      autoload :UserGroupsResponse, "cloudinary_account_provisioning/models/shared/usergroupsresponse.rb"
      autoload :UserRequest, "cloudinary_account_provisioning/models/shared/userrequest.rb"
      autoload :UserRequestRole, "cloudinary_account_provisioning/models/shared/userrequest_role.rb"
      autoload :UserSubAccountsResponse, "cloudinary_account_provisioning/models/shared/usersubaccountsresponse.rb"
      autoload :UsersResponse, "cloudinary_account_provisioning/models/shared/usersresponse.rb"
      autoload(
        :ValidateCedarPolicyRequest,
        "cloudinary_account_provisioning/models/shared/validatecedarpolicyrequest.rb"
      )
      autoload(
        :ValidateCedarPolicyResponse,
        "cloudinary_account_provisioning/models/shared/validatecedarpolicyresponse.rb"
      )
      autoload :Breakdown, "cloudinary_account_provisioning/models/shared/breakdown.rb"
      autoload :CustomAttributes, "cloudinary_account_provisioning/models/shared/custom_attributes.rb"
      autoload :Cycles, "cloudinary_account_provisioning/models/shared/cycles.rb"
      autoload :Data, "cloudinary_account_provisioning/models/shared/data.rb"
      autoload :DedicatedFor, "cloudinary_account_provisioning/models/shared/dedicated_for.rb"
      autoload :Details, "cloudinary_account_provisioning/models/shared/details.rb"
      autoload :EmailPreferences, "cloudinary_account_provisioning/models/shared/email_preferences.rb"
      autoload :Error, "cloudinary_account_provisioning/models/shared/error.rb"
      autoload :MetricUsage, "cloudinary_account_provisioning/models/shared/metric_usage.rb"
      autoload :MonthlyCycles, "cloudinary_account_provisioning/models/shared/monthly_cycles.rb"
      autoload :PolicyParameters, "cloudinary_account_provisioning/models/shared/policy_parameters.rb"
    end
  end
end
