# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: d128056de4ad

# typed: true
# frozen_string_literal: true

# Add your extra requires here (`bin/tapioca require` can be used to bootstrap this list)

require 'faraday'
require 'faraday/multipart'
require 'faraday/retry'
require 'multipart/post'
