# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 39a53c63a972

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module ServerVariables
      autoload :ServerRegion, "cld_provisioning/models/server_variables/server_region.rb"
    end
  end
end
