# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 6c0a9539afdf

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      autoload :AccessKey, "cld_provisioning/models/shared/accesskey.rb"
      autoload :AccessKeyRequest, "cld_provisioning/models/shared/accesskeyrequest.rb"
      autoload :AccessKeyUpdateRequest, "cld_provisioning/models/shared/accesskeyupdaterequest.rb"
      autoload :AccessKeysResponse, "cld_provisioning/models/shared/accesskeysresponse.rb"
      autoload :ApiAccessKey, "cld_provisioning/models/shared/apiaccesskey.rb"
      autoload :BillingUsageResponse, "cld_provisioning/models/shared/billingusageresponse.rb"
      autoload :BillingUsageResponseBreakdown, "cld_provisioning/models/shared/billingusageresponse_breakdown.rb"
      autoload :CedarError, "cld_provisioning/models/shared/cedarerror.rb"
      autoload :CedarSchemaResponse, "cld_provisioning/models/shared/cedarschemaresponse.rb"
      autoload :CloudAssetTypeBreakdown, "cld_provisioning/models/shared/cloudassettypebreakdown.rb"
      autoload :CreateRole, "cld_provisioning/models/shared/createrole.rb"
      autoload :CustomPoliciesResponse, "cld_provisioning/models/shared/custompoliciesresponse.rb"
      autoload :CustomPolicy, "cld_provisioning/models/shared/custompolicy.rb"
      autoload :CustomPolicyResponse, "cld_provisioning/models/shared/custompolicyresponse.rb"
      autoload :CustomPolicyResponseData, "cld_provisioning/models/shared/custompolicyresponsedata.rb"
      autoload :EffectivePoliciesResponse, "cld_provisioning/models/shared/effectivepoliciesresponse.rb"
      autoload :EffectivePolicy, "cld_provisioning/models/shared/effectivepolicy.rb"
      autoload :EffectiveRole, "cld_provisioning/models/shared/effectiverole.rb"
      autoload :InspectRequest, "cld_provisioning/models/shared/inspectrequest.rb"
      autoload :InspectRequestPolicyParameters, "cld_provisioning/models/shared/inspectrequest_policy_parameters.rb"
      autoload :ManagementTypeEnum, "cld_provisioning/models/shared/managementtypeenum.rb"
      autoload :OperationEnum, "cld_provisioning/models/shared/operationenum.rb"
      autoload :PermissionTypeEnum, "cld_provisioning/models/shared/permissiontypeenum.rb"
      autoload :PermissionsError, "cld_provisioning/models/shared/permissionserror.rb"
      autoload :Principal, "cld_provisioning/models/shared/principal.rb"
      autoload :PrincipalResponseData, "cld_provisioning/models/shared/principalresponsedata.rb"
      autoload(
        :PrincipalResponseDataPolicyParameters,
        "cld_provisioning/models/shared/principalresponsedata_policy_parameters.rb"
      )
      autoload :PrincipalRole, "cld_provisioning/models/shared/principalrole.rb"
      autoload :PrincipalRolesData, "cld_provisioning/models/shared/principalrolesdata.rb"
      autoload :PrincipalRolesInspectData, "cld_provisioning/models/shared/principalrolesinspectdata.rb"
      autoload :PrincipalRolesInspectResponse, "cld_provisioning/models/shared/principalrolesinspectresponse.rb"
      autoload(
        :PrincipalRolesInspectResponseData,
        "cld_provisioning/models/shared/principalrolesinspectresponse_data.rb"
      )
      autoload :PrincipalRolesResponse, "cld_provisioning/models/shared/principalrolesresponse.rb"
      autoload :PrincipalTypeEnum, "cld_provisioning/models/shared/principaltypeenum.rb"
      autoload :PrincipalsResponse, "cld_provisioning/models/shared/principalsresponse.rb"
      autoload :ProductEnvironment, "cld_provisioning/models/shared/productenvironment.rb"
      autoload :ProductEnvironmentRequest, "cld_provisioning/models/shared/productenvironmentrequest.rb"
      autoload :ProductEnvironmentUpdateRequest, "cld_provisioning/models/shared/productenvironmentupdaterequest.rb"
      autoload(
        :ProductEnvironmentUpdateRequestCustomAttributes,
        "cld_provisioning/models/shared/productenvironmentupdaterequest_custom_attributes.rb"
      )
      autoload :ProductEnvironmentsResponse, "cld_provisioning/models/shared/productenvironmentsresponse.rb"
      autoload :Role, "cld_provisioning/models/shared/role.rb"
      autoload :RoleResponse, "cld_provisioning/models/shared/roleresponse.rb"
      autoload :RoleResponseData, "cld_provisioning/models/shared/roleresponsedata.rb"
      autoload :RoleResponseData1, "cld_provisioning/models/shared/roleresponse_data1.rb"
      autoload :RoleToManage, "cld_provisioning/models/shared/roletomanage.rb"
      autoload :RoleToManagePolicyParameters, "cld_provisioning/models/shared/roletomanage_policy_parameters.rb"
      autoload :RolesResponse, "cld_provisioning/models/shared/rolesresponse.rb"
      autoload :ScopeTypeEnum, "cld_provisioning/models/shared/scopetypeenum.rb"
      autoload :Security, "cld_provisioning/models/shared/security.rb"
      autoload :SubAccountSummary, "cld_provisioning/models/shared/subaccountsummary.rb"
      autoload :SuccessResponse, "cld_provisioning/models/shared/successresponse.rb"
      autoload :SystemPoliciesResponse, "cld_provisioning/models/shared/systempoliciesresponse.rb"
      autoload :SystemPolicyResponseData, "cld_provisioning/models/shared/systempolicyresponsedata.rb"
      autoload(
        :SystemRolesAndPoliciesCatalogResponse,
        "cld_provisioning/models/shared/systemrolesandpoliciescatalogresponse.rb"
      )
      autoload :UpdateCustomPolicy, "cld_provisioning/models/shared/updatecustompolicy.rb"
      autoload :UpdatePrincipalRolesRequest, "cld_provisioning/models/shared/updateprincipalrolesrequest.rb"
      autoload :UpdateRolePrincipal, "cld_provisioning/models/shared/updateroleprincipal.rb"
      autoload(
        :UpdateRolePrincipalPolicyParameters,
        "cld_provisioning/models/shared/updateroleprincipal_policy_parameters.rb"
      )
      autoload :UpdateRolePrincipalsRequest, "cld_provisioning/models/shared/updateroleprincipalsrequest.rb"
      autoload :User, "cld_provisioning/models/shared/user.rb"
      autoload :UserGroup, "cld_provisioning/models/shared/usergroup.rb"
      autoload :UserGroupRequest, "cld_provisioning/models/shared/usergrouprequest.rb"
      autoload :UserGroupSummary, "cld_provisioning/models/shared/usergroupsummary.rb"
      autoload :UserGroupUser, "cld_provisioning/models/shared/usergroupuser.rb"
      autoload :UserGroupUsersResponse, "cld_provisioning/models/shared/usergroupusersresponse.rb"
      autoload :UserGroupsListResponse, "cld_provisioning/models/shared/usergroupslistresponse.rb"
      autoload :UserGroupsResponse, "cld_provisioning/models/shared/usergroupsresponse.rb"
      autoload :UserRequest, "cld_provisioning/models/shared/userrequest.rb"
      autoload :UserRequestRole, "cld_provisioning/models/shared/userrequest_role.rb"
      autoload :UserSubAccountsResponse, "cld_provisioning/models/shared/usersubaccountsresponse.rb"
      autoload :UsersResponse, "cld_provisioning/models/shared/usersresponse.rb"
      autoload :ValidateCedarPolicyRequest, "cld_provisioning/models/shared/validatecedarpolicyrequest.rb"
      autoload :ValidateCedarPolicyResponse, "cld_provisioning/models/shared/validatecedarpolicyresponse.rb"
      autoload :Breakdown, "cld_provisioning/models/shared/breakdown.rb"
      autoload :CustomAttributes, "cld_provisioning/models/shared/custom_attributes.rb"
      autoload :Cycles, "cld_provisioning/models/shared/cycles.rb"
      autoload :Data, "cld_provisioning/models/shared/data.rb"
      autoload :DedicatedFor, "cld_provisioning/models/shared/dedicated_for.rb"
      autoload :Details, "cld_provisioning/models/shared/details.rb"
      autoload :EmailPreferences, "cld_provisioning/models/shared/email_preferences.rb"
      autoload :Error, "cld_provisioning/models/shared/error.rb"
      autoload :MetricUsage, "cld_provisioning/models/shared/metric_usage.rb"
      autoload :MonthlyCycles, "cld_provisioning/models/shared/monthly_cycles.rb"
      autoload :PolicyParameters, "cld_provisioning/models/shared/policy_parameters.rb"
    end
  end
end
