# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require "faraday"
require "faraday/multipart"
require "faraday/retry"
require "sorbet-runtime"

require_relative "sdk_hooks/hooks"
require_relative "utils/retries"

module CloudinaryAccountProvisioning
  extend T::Sig

  class CldProvisioning
    extend T::Sig

    attr_accessor(
      :product_environments,
      :access_keys,
      :users,
      :user_groups,
      :billing_usage,
      :public,
      :system_policies,
      :custom_policies,
      :effective_policies,
      :roles,
      :principals
    )

    # Instantiates the SDK, configuring it with the provided parameters.
    #
    # @param client [Faraday::Connection, nil] The faraday HTTP client to use for all operations
    # @param retry_config [::CloudinaryAccountProvisioning::Utils::RetryConfig, nil] The retry configuration to use for all operations
    # @param timeout_ms [Integer, nil] Request timeout in milliseconds for all operations
    # @param security [Models::Shared::Security, nil] The security details required for authentication
    # @param security_source [Proc{|| Models::Shared::Security, nil}] A function that returns security details required for authentication
    # @param account_id [String, nil] Configures the account_id parameter for all supported operations
    # @param region [::CloudinaryAccountProvisioning::Models::ServerVariables::ServerRegion, nil] Allows setting the region variable for url substitution
    # @param host [String, nil] Allows setting the host variable for url substitution
    # @param server_idx [Integer, nil] The index of the server to use for all operations
    # @param server_url [String, nil] The server URL to use for all operations
    # @param url_params [Hash{Symbol => String}, nil] Parameters to optionally template the server URL with
    sig do
      params(
        client: T.nilable(Faraday::Connection),
        retry_config: T.nilable(::CloudinaryAccountProvisioning::Utils::RetryConfig),
        timeout_ms: T.nilable(Integer),
        security: T.nilable(Models::Shared::Security),
        security_source: T.nilable(T.proc.returns(Models::Shared::Security)),
        account_id: T.nilable(::String),
        region: T.nilable(::CloudinaryAccountProvisioning::Models::ServerVariables::ServerRegion),
        host: T.nilable(::String),
        server_idx: T.nilable(Integer),
        server_url: T.nilable(String),
        url_params: T.nilable(T::Hash[Symbol, String])
      )
        .void
    end
    def initialize(
      client: nil,
      retry_config: nil,
      timeout_ms: nil,
      security: nil,
      security_source: nil,
      account_id: nil,
      region: nil,
      host: nil,
      server_idx: nil,
      server_url: nil,
      url_params: nil
    )

      connection_options = {
        request: {
          params_encoder: Faraday::FlatParamsEncoder
        }
      }
      connection_options[:request][:timeout] = (timeout_ms.to_f / 1000) unless timeout_ms.nil?

      client ||= Faraday.new(**connection_options) do |f|
        f.request(:multipart, {flat_encode: true})
        # f.response :logger, nil, { headers: true, bodies: true, errors: true }
      end

      has_custom_server_variable = !region.nil? || !host.nil?
      region = region.nil? ? "api" : region.serialize
      host = host.nil? ? "api.cloudinary.com" : host
      if !server_url.nil?
        if !url_params.nil?
          server_url = Utils.template_url(server_url, url_params)
        elsif has_custom_server_variable
          url_params = {
            region: region,
            host: host
          }
          server_url = Utils.template_url(server_url, url_params)
        end
      end

      server_idx = 0 if server_idx.nil?

      server_params = [
        {
          region: region
        },
        {
          host: host
        }
      ]

      globals = {
        'parameters': {
          'queryParam': {},
          'pathParam': {
            'account_id': account_id
          },
          'header': {}
        }
      }
      hooks = SDKHooks::Hooks.new
      @sdk_configuration = SDKConfiguration.new(
        client,
        hooks,
        retry_config,
        timeout_ms,
        security,
        security_source,
        server_url,
        server_idx,
        server_params,
        globals
      )
      @sdk_configuration = hooks.sdk_init(config: @sdk_configuration)
      init_sdks
    end

    sig { void }
    def init_sdks
      @product_environments = ProductEnvironments.new(@sdk_configuration)
      @access_keys = AccessKeys.new(@sdk_configuration)
      @users = Users.new(@sdk_configuration)
      @user_groups = UserGroups.new(@sdk_configuration)
      @billing_usage = BillingUsage.new(@sdk_configuration)
      @public = Public.new(@sdk_configuration)
      @system_policies = SystemPolicies.new(@sdk_configuration)
      @custom_policies = CustomPolicies.new(@sdk_configuration)
      @effective_policies = EffectivePolicies.new(@sdk_configuration)
      @roles = Roles.new(@sdk_configuration)
      @principals = Principals.new(@sdk_configuration)
    end

    sig { params(base_url: String, url_variables: T.nilable(T::Hash[Symbol, T.any(String, T::Enum)])).returns(String) }
    def get_url(base_url:, url_variables: nil)
      sd_base_url, sd_options = @sdk_configuration.get_server_details

      if base_url.nil?
        base_url = sd_base_url
      end

      if url_variables.nil?
        url_variables = sd_options
      end

      return Utils.template_url(base_url, url_variables)
    end

  end
end
