# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require "faraday"
require "faraday/multipart"
require "faraday/retry"
require "sorbet-runtime"

require_relative "sdk_hooks/hooks"
require_relative "utils/retries"

module CloudinaryAccountProvisioning
  extend T::Sig

  SERVERS = T.let(
    [
      # 1 - Regional API endpoints for optimal performance.
      "https://{region}.cloudinary.com",
      # 1 - Custom domains for enterprise deployments.
      "https://{host}"
    ].freeze,
    T::Array[String]
  )
  # Contains the list of servers available to the SDK

  class SDKConfiguration
    extend T::Sig

    sig { returns(T.nilable(Faraday::Connection)) }
    attr_accessor :client

    sig { returns(::CloudinaryAccountProvisioning::SDKHooks::Hooks) }
    attr_accessor :hooks

    sig { returns(T.nilable(::CloudinaryAccountProvisioning::Utils::RetryConfig)) }
    attr_accessor :retry_config

    sig { returns(T.nilable(Float)) }
    attr_accessor :timeout

    sig { returns(T.nilable(T.proc.returns(T.nilable(Models::Shared::Security)))) }
    attr_accessor :security_source

    sig { returns(T.nilable(String)) }
    attr_accessor :server_url

    sig { returns(T.nilable(Integer)) }
    attr_accessor :server_idx

    sig { returns(T::Array[T::Hash[Symbol, String]]) }
    attr_accessor :server_params

    sig { returns(T::Hash[Symbol, T::Hash[Symbol, T::Hash[Symbol, Object]]]) }
    attr_accessor :globals

    sig { returns(String) }
    attr_accessor :language

    sig { returns(String) }
    attr_accessor :openapi_doc_version

    sig { returns(String) }
    attr_accessor :sdk_version

    sig { returns(String) }
    attr_accessor :gen_version

    sig { returns(String) }
    attr_accessor :user_agent

    sig do
      params(
        client: T.nilable(Faraday::Connection),
        hooks: ::CloudinaryAccountProvisioning::SDKHooks::Hooks,
        retry_config: T.nilable(::CloudinaryAccountProvisioning::Utils::RetryConfig),
        timeout_ms: T.nilable(Integer),
        security: T.nilable(Models::Shared::Security),
        security_source: T.nilable(T.proc.returns(Models::Shared::Security)),
        server_url: T.nilable(String),
        server_idx: T.nilable(Integer),
        server_params: T::Array[T::Hash[Symbol, String]],
        globals: T.nilable(T::Hash[Symbol, T::Hash[Symbol, T::Hash[Symbol, Object]]])
      )
        .void
    end
    def initialize(
      client,
      hooks,
      retry_config,
      timeout_ms,
      security,
      security_source,
      server_url,
      server_idx,
      server_params,
      globals
    )
      @client = client
      @hooks = hooks
      @retry_config = retry_config
      @server_url = server_url
      @timeout = (timeout_ms.to_f / 1000) unless timeout_ms.nil?
      @server_idx = server_idx.nil? ? 0 : server_idx
      if @server_idx.negative? || @server_idx >= SERVERS.length
        raise StandardError, "Invalid server index #{server_idx}"
      end

      @server_params = server_params
      if !security_source.nil?
        @security_source = security_source
      elsif !security.nil?
        @security_source = -> { security }
      end

      @globals = globals.nil? ? {} : globals
      @language = "ruby"
      @openapi_doc_version = "0.2.1"
      @sdk_version = "0.1.0"
      @gen_version = "2.881.17"
      @user_agent = "speakeasy-sdk/ruby 0.1.0 2.881.17 0.2.1 cloudinary-account-provisioning"
    end

    sig { returns([String, T::Hash[Symbol, String]]) }
    def get_server_details
      return [@server_url.delete_suffix("/"), {}] if !@server_url.nil?
      @server_idx = T.must(@server_idx)
      [T.must(SERVERS[@server_idx]), T.must(@server_params[@server_idx])]
    end
  end
end
