# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class AccessKey
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the access key.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("name")}}
        )
        # The API key.
        field(
          :api_key,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("api_key")}}
        )
        # The API secret.
        field(
          :api_secret,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("api_secret")}}
        )
        # The date when the access key was created.
        field(
          :created_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("created_at"),
              'decoder': ::CloudinaryAccountProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # The date when the access key was last updated.
        field(
          :updated_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("updated_at"),
              'decoder': ::CloudinaryAccountProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # Whether the access key is enabled or disabled.
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("enabled")}}
        )

        sig {
          params(
            name: T.nilable(::String),
            api_key: T.nilable(::String),
            api_secret: T.nilable(::String),
            created_at: T.nilable(::DateTime),
            updated_at: T.nilable(::DateTime),
            enabled: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(name: nil, api_key: nil, api_secret: nil, created_at: nil, updated_at: nil, enabled: nil)
          @name = name
          @api_key = api_key
          @api_secret = api_secret
          @created_at = created_at
          @updated_at = updated_at
          @enabled = enabled
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @api_key == other.api_key
          return false unless @api_secret == other.api_secret
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @enabled == other.enabled
          true
        end
      end
    end
  end
end
