# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class CedarError
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :cedar_message,
          ::String,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("cedar_message"),
              required: true
            }
          }
        )

        field(
          :cedar_code,
          ::String,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("cedar_code"),
              required: true
            }
          }
        )

        sig { params(cedar_message: ::String, cedar_code: ::String).void }
        def initialize(cedar_message:, cedar_code:)
          @cedar_message = cedar_message
          @cedar_code = cedar_code
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @cedar_message == other.cedar_message
          return false unless @cedar_code == other.cedar_code
          true
        end
      end
    end
  end
end
