# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class CreateRole
        extend T::Sig
        include Crystalline::MetadataFields

        # Specifies whether the permission applies globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID `"fg3841spr"`). **Note:** This attrubute is immutable.
        # - global
        # - content
        #
        field(
          :permission_type,
          ::String,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("permission_type"),
              required: true
            }
          }
        )
        # Specifies where the role/policy is applied, either at the account level or within product environments.
        field(
          :scope_type,
          Models::Shared::ScopeTypeEnum,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("scope_type"),
              required: true,
              'decoder': ::CloudinaryAccountProvisioning::Utils.open_enum_from_string(
                Models::Shared::ScopeTypeEnum,
                false
              )
            }
          }
        )
        # The name of the role.
        field(
          :name,
          ::String,
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("name"), required: true}}
        )
        # The unique identifier for the role.
        #
        # * **When creating a new role**: If not provided, the system will auto-generate the ID.
        # * **When updating a role**: Specify the ID of the role you want to update.
        #
        field(
          :id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("id")}}
        )
        # A list of system permission policy IDs to be included in the role.
        #
        # **Tip:** Get the list of all available predefined policies using the [Get system policies](#tag/policies/get/policies) method.
        #
        field(
          :system_policy_ids,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("system_policy_ids")}}
        )
        # A short description of the role.
        field(
          :description,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("description")}}
        )

        sig {
          params(
            permission_type: ::String,
            scope_type: Models::Shared::ScopeTypeEnum,
            name: ::String,
            id: T.nilable(::String),
            system_policy_ids: T.nilable(T::Array[::String]),
            description: T.nilable(::String)
          )
            .void
        }
        def initialize(permission_type:, scope_type:, name:, id: nil, system_policy_ids: nil, description: nil)
          @permission_type = permission_type
          @scope_type = scope_type
          @name = name
          @id = id
          @system_policy_ids = system_policy_ids
          @description = description
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @permission_type == other.permission_type
          return false unless @scope_type == other.scope_type
          return false unless @name == other.name
          return false unless @id == other.id
          return false unless @system_policy_ids == other.system_policy_ids
          return false unless @description == other.description
          true
        end
      end
    end
  end
end
