# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class Data
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :principals,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PrincipalRole)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("principals")}}
        )

        field(
          :custom_policies,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::EffectivePolicy)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("custom_policies")}}
        )

        sig {
          params(
            principals: T.nilable(T::Array[Models::Shared::PrincipalRole]),
            custom_policies: T.nilable(T::Array[Models::Shared::EffectivePolicy])
          )
            .void
        }
        def initialize(principals: nil, custom_policies: nil)
          @principals = principals
          @custom_policies = custom_policies
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @principals == other.principals
          return false unless @custom_policies == other.custom_policies
          true
        end
      end
    end
  end
end
