# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared
      # PermissionTypeEnum - Specifies whether permissions apply globally or to specific content.
      class PermissionTypeEnum
        include ::Crystalline::Enum
        enums do
          GLOBAL = new("global")
          CONTENT = new("content")
        end

        open!
      end
    end
  end
end
