# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class PrincipalRolesInspectResponse
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :data,
          Crystalline::Nilable.new(Models::Shared::PrincipalRolesInspectResponseData),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("data")}}
        )

        field(
          :next_cursor,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("next_cursor")}}
        )

        sig {
          params(data: T.nilable(Models::Shared::PrincipalRolesInspectResponseData), next_cursor: T.nilable(::String))
            .void
        }
        def initialize(data: nil, next_cursor: nil)
          @data = data
          @next_cursor = next_cursor
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @data == other.data
          return false unless @next_cursor == other.next_cursor
          true
        end
      end
    end
  end
end
