# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class Role
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the role.
        field(
          :name,
          ::String,
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("name"), required: true}}
        )
        # A list of system permission policy IDs to be included in the role.
        #
        # **Tip:** Get the list of all available predefined policies using the [Get system policies](#tag/policies/get/policies) method.
        #
        field(
          :system_policy_ids,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("system_policy_ids")}}
        )
        # A short description of the role.
        field(
          :description,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("description")}}
        )

        sig {
          params(name: ::String, system_policy_ids: T.nilable(T::Array[::String]), description: T.nilable(::String))
            .void
        }
        def initialize(name:, system_policy_ids: nil, description: nil)
          @name = name
          @system_policy_ids = system_policy_ids
          @description = description
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @system_policy_ids == other.system_policy_ids
          return false unless @description == other.description
          true
        end
      end
    end
  end
end
