# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class RoleResponseData
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the role.
        field(
          :id,
          ::String,
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("id"), required: true}}
        )
        # The name of the role.
        field(
          :name,
          ::String,
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("name"), required: true}}
        )
        # Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
        field(
          :management_type,
          Models::Shared::ManagementTypeEnum,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("management_type"),
              required: true,
              'decoder': ::CloudinaryAccountProvisioning::Utils.open_enum_from_string(
                Models::Shared::ManagementTypeEnum,
                false
              )
            }
          }
        )
        # Specifies whether the permission applies globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
        #
        #     - global
        #
        #     - content
        #
        field(
          :permission_type,
          ::String,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("permission_type"),
              required: true
            }
          }
        )
        # Specifies where the role/policy is applied, either at the account level or within product environments.
        field(
          :scope_type,
          Models::Shared::ScopeTypeEnum,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("scope_type"),
              required: true,
              'decoder': ::CloudinaryAccountProvisioning::Utils.open_enum_from_string(
                Models::Shared::ScopeTypeEnum,
                false
              )
            }
          }
        )
        # The permission policy creation timestamp in epoch time.
        field(
          :created_at,
          ::Integer,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("created_at"),
              required: true
            }
          }
        )
        # The permission policy last updated timestamp in epoch time.
        field(
          :updated_at,
          ::Integer,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("updated_at"),
              required: true
            }
          }
        )
        # For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
        # - The content type can be: `folder_id` or `collection_id`.
        # - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
        #
        field(
          :policy_parameters,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("policy_parameters")}}
        )
        # A short description of the role.
        field(
          :description,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("description")}}
        )

        sig {
          params(
            id: ::String,
            name: ::String,
            management_type: Models::Shared::ManagementTypeEnum,
            permission_type: ::String,
            scope_type: Models::Shared::ScopeTypeEnum,
            created_at: ::Integer,
            updated_at: ::Integer,
            policy_parameters: T.nilable(T::Array[::String]),
            description: T.nilable(::String)
          )
            .void
        }
        def initialize(
          id:,
          name:,
          management_type:,
          permission_type:,
          scope_type:,
          created_at:,
          updated_at:,
          policy_parameters: nil,
          description: nil
        )
          @id = id
          @name = name
          @management_type = management_type
          @permission_type = permission_type
          @scope_type = scope_type
          @created_at = created_at
          @updated_at = updated_at
          @policy_parameters = policy_parameters
          @description = description
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @management_type == other.management_type
          return false unless @permission_type == other.permission_type
          return false unless @scope_type == other.scope_type
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @policy_parameters == other.policy_parameters
          return false unless @description == other.description
          true
        end
      end
    end
  end
end
