# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared
      # Defines the content instance that the role applies to. Specify the content type (`folder_id` or `collection_id`) and its corresponding ID. For example, `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
      class RoleToManagePolicyParameters
        extend T::Sig
        include Crystalline::MetadataFields

        def initialize
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          true
        end
      end
    end
  end
end
