# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class RoleToManage
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the role you want to assign.
        field(
          :id,
          ::String,
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("id"), required: true}}
        )
        # The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is "prodenv".
        field(
          :scope_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("scope_id")}}
        )
        # Defines the content instance that the role applies to. Specify the content type (`folder_id` or `collection_id`) and its corresponding ID. For example, `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
        field(
          :policy_parameters,
          Crystalline::Nilable.new(Models::Shared::RoleToManagePolicyParameters),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("policy_parameters")}}
        )

        sig {
          params(
            id: ::String,
            scope_id: T.nilable(::String),
            policy_parameters: T.nilable(Models::Shared::RoleToManagePolicyParameters)
          )
            .void
        }
        def initialize(id:, scope_id: nil, policy_parameters: nil)
          @id = id
          @scope_id = scope_id
          @policy_parameters = policy_parameters
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @scope_id == other.scope_id
          return false unless @policy_parameters == other.policy_parameters
          true
        end
      end
    end
  end
end
