# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class Security
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :provisioning_api_key,
          ::String,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("provisioning_api_key"),
              required: true
            },
            'security': {'scheme': true, 'type': "http", 'sub_type': "custom", 'field_name': "provisioning_api_key"}
          }
        )

        field(
          :provisioning_api_secret,
          ::String,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("provisioning_api_secret"),
              required: true
            },
            'security': {'scheme': true, 'type': "http", 'sub_type': "custom", 'field_name': "provisioning_api_secret"}
          }
        )

        sig { params(provisioning_api_key: ::String, provisioning_api_secret: ::String).void }
        def initialize(provisioning_api_key:, provisioning_api_secret:)
          @provisioning_api_key = provisioning_api_key
          @provisioning_api_secret = provisioning_api_secret
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @provisioning_api_key == other.provisioning_api_key
          return false unless @provisioning_api_secret == other.provisioning_api_secret
          true
        end
      end
    end
  end
end
