# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class UpdateRolePrincipalsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Specifies the operation to perform. Use `add` to associate or `remove` to disassociate.
        field(
          :operation,
          Crystalline::Nilable.new(Models::Shared::OperationEnum),
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("operation"),
              'decoder': ::CloudinaryAccountProvisioning::Utils.enum_from_string(Models::Shared::OperationEnum, true)
            }
          }
        )

        field(
          :principals,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::UpdateRolePrincipal)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("principals")}}
        )

        sig {
          params(
            operation: T.nilable(Models::Shared::OperationEnum),
            principals: T.nilable(T::Array[Models::Shared::UpdateRolePrincipal])
          )
            .void
        }
        def initialize(operation: nil, principals: nil)
          @operation = operation
          @principals = principals
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @operation == other.operation
          return false unless @principals == other.principals
          true
        end
      end
    end
  end
end
