# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class UpdateRolePrincipal
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of principal.
        field(
          :principal_type,
          Models::Shared::PrincipalTypeEnum,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("principal_type"),
              required: true,
              'decoder': ::CloudinaryAccountProvisioning::Utils.open_enum_from_string(
                Models::Shared::PrincipalTypeEnum,
                false
              )
            }
          }
        )
        # The unique identifier of the principal.
        field(
          :principal_id,
          ::String,
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("principal_id"),
              required: true
            }
          }
        )
        # For roles with `permission_type` set to `content`, provide the ID of the specific folder or collection you want the role to apply to, for example, `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement`, written in Cedar language.
        field(
          :policy_parameters,
          Crystalline::Nilable.new(Models::Shared::UpdateRolePrincipalPolicyParameters),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("policy_parameters")}}
        )
        # The ID of a specific product environment where the role is applied. This parameter is only relevant if `scope_type` is "prodenv".
        field(
          :scope_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("scope_id")}}
        )

        sig {
          params(
            principal_type: Models::Shared::PrincipalTypeEnum,
            principal_id: ::String,
            policy_parameters: T.nilable(Models::Shared::UpdateRolePrincipalPolicyParameters),
            scope_id: T.nilable(::String)
          )
            .void
        }
        def initialize(principal_type:, principal_id:, policy_parameters: nil, scope_id: nil)
          @principal_type = principal_type
          @principal_id = principal_id
          @policy_parameters = policy_parameters
          @scope_id = scope_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @principal_type == other.principal_type
          return false unless @principal_id == other.principal_id
          return false unless @policy_parameters == other.policy_parameters
          return false unless @scope_id == other.scope_id
          true
        end
      end
    end
  end
end
