# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class UpdatePrincipalRolesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Specifies the operation to perform. Use `add` to associate or `remove` to disassociate.
        field(
          :operation,
          Crystalline::Nilable.new(Models::Shared::OperationEnum),
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("operation"),
              'decoder': ::CloudinaryAccountProvisioning::Utils.enum_from_string(Models::Shared::OperationEnum, true)
            }
          }
        )

        field(
          :principal,
          Crystalline::Nilable.new(Models::Shared::Principal),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("principal")}}
        )

        field(
          :roles,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::RoleToManage)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("roles")}}
        )

        sig {
          params(
            operation: T.nilable(Models::Shared::OperationEnum),
            principal: T.nilable(Models::Shared::Principal),
            roles: T.nilable(T::Array[Models::Shared::RoleToManage])
          )
            .void
        }
        def initialize(operation: nil, principal: nil, roles: nil)
          @operation = operation
          @principal = principal
          @roles = roles
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @operation == other.operation
          return false unless @principal == other.principal
          return false unless @roles == other.roles
          true
        end
      end
    end
  end
end
