# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared
      # User group summary.
      class UserGroupSummary
        extend T::Sig
        include Crystalline::MetadataFields

        # The user group's ID.
        field(
          :id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("id")}}
        )
        # The user group's name.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("name")}}
        )

        sig { params(id: T.nilable(::String), name: T.nilable(::String)).void }
        def initialize(id: nil, name: nil)
          @id = id
          @name = name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @name == other.name
          true
        end
      end
    end
  end
end
