# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared
      # User details.
      class User
        extend T::Sig
        include Crystalline::MetadataFields

        # The user's ID.
        field(
          :id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("id")}}
        )
        # The user's name.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("name")}}
        )
        # The user's first name.
        field(
          :first_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("first_name")}}
        )
        # The user's last name.
        field(
          :last_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("last_name")}}
        )
        # The user's role.
        field(
          :role,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("role")}}
        )
        # The user's email.
        field(
          :email,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("email")}}
        )
        # Whether the user is pending.
        field(
          :pending,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("pending")}}
        )
        # Whether the user is enabled.
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("enabled")}}
        )
        # The date when the user was created.
        field(
          :created_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("created_at"),
              'decoder': ::CloudinaryAccountProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # The date when the user was last updated.
        field(
          :updated_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("updated_at"),
              'decoder': ::CloudinaryAccountProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # The date when the user was last logged in.
        field(
          :last_login,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("last_login"),
              'decoder': ::CloudinaryAccountProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )

        field(
          :all_sub_accounts,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("all_sub_accounts")}}
        )
        # The list of authentication providers for the user.
        field(
          :providers,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("providers")}}
        )
        # The user's email preferences.
        field(
          :email_preferences,
          Crystalline::Nilable.new(Models::Shared::EmailPreferences),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("email_preferences")}}
        )
        # The account ID.
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("account_id")}}
        )
        # Whether two-factor authentication is enabled.
        field(
          :two_factor,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("two_factor")}}
        )
        # The user's status.
        field(
          :status,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("status")}}
        )
        # Whether the user is a root user.
        field(
          :root,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("root")}}
        )
        # The user's technical role.
        field(
          :technical_role,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("technical_role")}}
        )
        # The number of groups the user belongs to.
        field(
          :group_count,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("group_count")}}
        )
        # The number of sub-accounts the user has access to.
        field(
          :sub_account_count,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("sub_account_count")}}
        )

        sig {
          params(
            id: T.nilable(::String),
            name: T.nilable(::String),
            first_name: T.nilable(::String),
            last_name: T.nilable(::String),
            role: T.nilable(::String),
            email: T.nilable(::String),
            pending: T.nilable(T::Boolean),
            enabled: T.nilable(T::Boolean),
            created_at: T.nilable(::DateTime),
            updated_at: T.nilable(::DateTime),
            last_login: T.nilable(::DateTime),
            all_sub_accounts: T.nilable(T::Boolean),
            providers: T.nilable(T::Array[::String]),
            email_preferences: T.nilable(Models::Shared::EmailPreferences),
            account_id: T.nilable(::String),
            two_factor: T.nilable(T::Boolean),
            status: T.nilable(::String),
            root: T.nilable(T::Boolean),
            technical_role: T.nilable(::String),
            group_count: T.nilable(::Integer),
            sub_account_count: T.nilable(::Integer)
          )
            .void
        }
        def initialize(
          id: nil,
          name: nil,
          first_name: nil,
          last_name: nil,
          role: nil,
          email: nil,
          pending: nil,
          enabled: nil,
          created_at: nil,
          updated_at: nil,
          last_login: nil,
          all_sub_accounts: nil,
          providers: nil,
          email_preferences: nil,
          account_id: nil,
          two_factor: nil,
          status: nil,
          root: nil,
          technical_role: nil,
          group_count: nil,
          sub_account_count: nil
        )
          @id = id
          @name = name
          @first_name = first_name
          @last_name = last_name
          @role = role
          @email = email
          @pending = pending
          @enabled = enabled
          @created_at = created_at
          @updated_at = updated_at
          @last_login = last_login
          @all_sub_accounts = all_sub_accounts
          @providers = providers
          @email_preferences = email_preferences
          @account_id = account_id
          @two_factor = two_factor
          @status = status
          @root = root
          @technical_role = technical_role
          @group_count = group_count
          @sub_account_count = sub_account_count
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @first_name == other.first_name
          return false unless @last_name == other.last_name
          return false unless @role == other.role
          return false unless @email == other.email
          return false unless @pending == other.pending
          return false unless @enabled == other.enabled
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @last_login == other.last_login
          return false unless @all_sub_accounts == other.all_sub_accounts
          return false unless @providers == other.providers
          return false unless @email_preferences == other.email_preferences
          return false unless @account_id == other.account_id
          return false unless @two_factor == other.two_factor
          return false unless @status == other.status
          return false unless @root == other.root
          return false unless @technical_role == other.technical_role
          return false unless @group_count == other.group_count
          return false unless @sub_account_count == other.sub_account_count
          true
        end
      end
    end
  end
end
