# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Shared

      class UserGroupsResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # A list of user groups.
        field(
          :user_groups,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::UserGroup)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("user_groups")}}
        )

        sig { params(user_groups: T.nilable(T::Array[Models::Shared::UserGroup])).void }
        def initialize(user_groups: nil)
          @user_groups = user_groups
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @user_groups == other.user_groups
          true
        end
      end
    end
  end
end
