# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations

      class CreateProductEnvironmentRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Product environment details.
        field(
          :product_environment_request,
          Models::Shared::ProductEnvironmentRequest,
          {'request': {'media_type': "application/json"}}
        )
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig {
          params(
            product_environment_request: Models::Shared::ProductEnvironmentRequest,
            account_id: T.nilable(::String)
          )
            .void
        }
        def initialize(product_environment_request:, account_id: nil)
          @product_environment_request = product_environment_request
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @product_environment_request == other.product_environment_request
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
