# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations
      # User details.
      class CreateUserRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The user's name.
        field(
          :name,
          ::String,
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("name"), required: true}}
        )
        # A unique email address, which serves as the login name and notification address.
        field(
          :email,
          ::String,
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("email"), required: true}}
        )
        # The role to assign.
        field(
          :role,
          Crystalline::Nilable.new(Models::Operations::Role),
          {
            'format_json': {
              'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("role"),
              'decoder': ::CloudinaryAccountProvisioning::Utils.enum_from_string(Models::Operations::Role, true)
            }
          }
        )
        # A list of product environment IDs that this user can access. Ignored if the role is `master_admin`.
        # **Default**: all product environments.
        #
        field(
          :sub_account_ids,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("sub_account_ids")}}
        )
        # Whether the user is enabled. **Default**: true.
        #
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CloudinaryAccountProvisioning::Utils.field_name("enabled")}}
        )

        sig {
          params(
            name: ::String,
            email: ::String,
            role: T.nilable(Models::Operations::Role),
            sub_account_ids: T.nilable(T::Array[::String]),
            enabled: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(name:, email:, role: nil, sub_account_ids: nil, enabled: nil)
          @name = name
          @email = email
          @role = role
          @sub_account_ids = sub_account_ids
          @enabled = enabled
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @email == other.email
          return false unless @role == other.role
          return false unless @sub_account_ids == other.sub_account_ids
          return false unless @enabled == other.enabled
          true
        end
      end
    end
  end
end
