# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations

      class DeleteRoleRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier for the role.
        field :role_id, ::String, {'path_param': {'field_name': "role_id", 'style': "simple", 'explode': false}}
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # Determines whether the role should be deleted when it has associated principals.
        # - `true`: Deletes the role even if it has associated principals.
        # - `false` (default): Prevents deletion if the role has associated principals. You must manually unassociate the principals before deleting the role.
        #
        field(
          :force,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'query_param': {'field_name': "force", 'style': "form", 'explode': true}}
        )

        sig { params(role_id: ::String, account_id: T.nilable(::String), force: T.nilable(T::Boolean)).void }
        def initialize(role_id:, account_id: nil, force: nil)
          @role_id = role_id
          @account_id = account_id
          @force = force
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @role_id == other.role_id
          return false unless @account_id == other.account_id
          return false unless @force == other.force
          true
        end
      end
    end
  end
end
