# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations

      class GetCustomPoliciesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # Specifies the level for retrieving policies or roles, either at the account level or within product environments.
        field(
          :scope_type,
          Crystalline::Nilable.new(Models::Shared::ScopeTypeEnum),
          {'query_param': {'field_name': "scope_type", 'style': "form", 'explode': true}}
        )
        # The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is "prodenv".
        # - <product_environment_id>
        #
        field(
          :scope_id,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "scope_id", 'style': "form", 'explode': true}}
        )
        # A pagination cursor for fetching subsequent results.
        field(
          :cursor,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "cursor", 'style': "form", 'explode': true}}
        )
        # Filter policies by enabled status (true/false).
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'query_param': {'field_name': "enabled", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            account_id: T.nilable(::String),
            scope_type: T.nilable(Models::Shared::ScopeTypeEnum),
            scope_id: T.nilable(::String),
            cursor: T.nilable(::String),
            enabled: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(account_id: nil, scope_type: nil, scope_id: nil, cursor: nil, enabled: nil)
          @account_id = account_id
          @scope_type = scope_type
          @scope_id = scope_id
          @cursor = cursor
          @enabled = enabled
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @account_id == other.account_id
          return false unless @scope_type == other.scope_type
          return false unless @scope_id == other.scope_id
          return false unless @cursor == other.cursor
          return false unless @enabled == other.enabled
          true
        end
      end
    end
  end
end
