# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations

      class GetCustomPolicyRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier for the custom permission policy.
        field :policy_id, ::String, {'path_param': {'field_name': "policy_id", 'style': "simple", 'explode': false}}
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig { params(policy_id: ::String, account_id: T.nilable(::String)).void }
        def initialize(policy_id:, account_id: nil)
          @policy_id = policy_id
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @policy_id == other.policy_id
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
