# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations

      class GetEffectivePoliciesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # Specifies the level for retrieving policies or roles, either at the account level or within product environments.
        field(
          :scope_type,
          Crystalline::Nilable.new(Models::Shared::ScopeTypeEnum),
          {'query_param': {'field_name': "scope_type", 'style': "form", 'explode': true}}
        )
        # The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is "prodenv".
        # - <product_environment_id>
        #
        field(
          :scope_id,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "scope_id", 'style': "form", 'explode': true}}
        )
        # The type of principal you want to retrieve roles or permission policies for.
        field(
          :principal_type,
          Crystalline::Nilable.new(Models::Shared::PrincipalTypeEnum),
          {'query_param': {'field_name': "principal_type", 'style': "form", 'explode': true}}
        )
        # The unique identifier of the principal you want to retrieve roles or permission policies for.
        #
        # **Notes:**
        #
        # * This parameter is mandatory if `principal_type` is provided.
        # * Ensure the specified ID belongs to a principle of the specified type.
        #
        field(
          :principal_id,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "principal_id", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            account_id: T.nilable(::String),
            scope_type: T.nilable(Models::Shared::ScopeTypeEnum),
            scope_id: T.nilable(::String),
            principal_type: T.nilable(Models::Shared::PrincipalTypeEnum),
            principal_id: T.nilable(::String)
          )
            .void
        }
        def initialize(account_id: nil, scope_type: nil, scope_id: nil, principal_type: nil, principal_id: nil)
          @account_id = account_id
          @scope_type = scope_type
          @scope_id = scope_id
          @principal_type = principal_type
          @principal_id = principal_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @account_id == other.account_id
          return false unless @scope_type == other.scope_type
          return false unless @scope_id == other.scope_id
          return false unless @principal_type == other.principal_type
          return false unless @principal_id == other.principal_id
          true
        end
      end
    end
  end
end
