# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations

      class GetUsersRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # Whether to return pending users. **Default**: `false` (all users)
        #
        field(
          :pending,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'query_param': {'field_name': "pending", 'style': "form", 'explode': true}}
        )
        # A list of up to 100 user IDs.  When provided, other parameters are ignored.
        field(
          :ids,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'query_param': {'field_name': "ids", 'style': "form", 'explode': true}}
        )
        # A list of up to 100 user Emails.  When provided, other parameters are ignored.
        field(
          :emails,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'query_param': {'field_name': "emails", 'style': "form", 'explode': true}}
        )
        # Returns users where the name begins with the specified case-insensitive string.
        field(
          :prefix,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "prefix", 'style': "form", 'explode': true}}
        )
        # Only returns users who have access to the specified account.
        field(
          :sub_account_id,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "sub_account_id", 'style': "form", 'explode': true}}
        )
        # Specifies a date range for last login.
        field(
          :last_login,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'query_param': {'field_name': "last_login", 'style': "form", 'explode': true}}
        )
        # All last logins after this date, given in the format: yyyy-mm-dd.
        #
        field(
          :from,
          Crystalline::Nilable.new(::Date),
          {'query_param': {'field_name': "from", 'style': "form", 'explode': true}}
        )
        # All last logins before this date, given in the format: yyyy-mm-dd.
        #
        field(
          :to,
          Crystalline::Nilable.new(::Date),
          {'query_param': {'field_name': "to", 'style': "form", 'explode': true}}
        )
        # Whether to return users who last logged in within the specified date range (include) or those who didn't
        # last log in within the range (exclude). **Possible values**: `include`, `exclude`. **Default**: `include`.
        #
        field(
          :union_type,
          Crystalline::Nilable.new(Models::Operations::UnionType),
          {'query_param': {'field_name': "union_type", 'style': "form", 'explode': true}}
        )
        # Control the order of returned users. **Possible values**: `desc` (default), `asc`.
        #
        field(
          :sort_order,
          Crystalline::Nilable.new(Models::Operations::QueryParamSortOrder),
          {'query_param': {'field_name': "sort_order", 'style': "form", 'explode': true}}
        )

        field(
          :sort_by,
          Crystalline::Nilable.new(Models::Operations::QueryParamSortBy),
          {'query_param': {'field_name': "sort_by", 'style': "form", 'explode': true}}
        )

        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )

        field(
          :page_size,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page_size", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            account_id: T.nilable(::String),
            pending: T.nilable(T::Boolean),
            ids: T.nilable(T::Array[::String]),
            emails: T.nilable(T::Array[::String]),
            prefix: T.nilable(::String),
            sub_account_id: T.nilable(::String),
            last_login: T.nilable(T::Boolean),
            from: T.nilable(::Date),
            to: T.nilable(::Date),
            union_type: T.nilable(Models::Operations::UnionType),
            sort_order: T.nilable(Models::Operations::QueryParamSortOrder),
            sort_by: T.nilable(Models::Operations::QueryParamSortBy),
            page: T.nilable(::Integer),
            page_size: T.nilable(::Integer)
          )
            .void
        }
        def initialize(
          account_id: nil,
          pending: nil,
          ids: nil,
          emails: nil,
          prefix: nil,
          sub_account_id: nil,
          last_login: nil,
          from: nil,
          to: nil,
          union_type: nil,
          sort_order: nil,
          sort_by: nil,
          page: nil,
          page_size: nil
        )
          @account_id = account_id
          @pending = pending
          @ids = ids
          @emails = emails
          @prefix = prefix
          @sub_account_id = sub_account_id
          @last_login = last_login
          @from = from
          @to = to
          @union_type = union_type
          @sort_order = sort_order
          @sort_by = sort_by
          @page = page
          @page_size = page_size
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @account_id == other.account_id
          return false unless @pending == other.pending
          return false unless @ids == other.ids
          return false unless @emails == other.emails
          return false unless @prefix == other.prefix
          return false unless @sub_account_id == other.sub_account_id
          return false unless @last_login == other.last_login
          return false unless @from == other.from
          return false unless @to == other.to
          return false unless @union_type == other.union_type
          return false unless @sort_order == other.sort_order
          return false unless @sort_by == other.sort_by
          return false unless @page == other.page
          return false unless @page_size == other.page_size
          true
        end
      end
    end
  end
end
