# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations
      # SortBy - Which response parameter to sort by. **Possible values**: `api_key`, `created_at`, `name`, `enabled`.
      #
      class SortBy < T::Enum
        enums do
          API_KEY = new("api_key")
          CREATED_AT = new("created_at")
          NAME = new("name")
          ENABLED = new("enabled")
        end
      end
    end
  end
end
