# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations

      class UpdatePrincipalRolesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Principal and roles details.
        field(
          :update_principal_roles_request,
          Models::Shared::UpdatePrincipalRolesRequest,
          {'request': {'media_type': "application/json"}}
        )
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig {
          params(
            update_principal_roles_request: Models::Shared::UpdatePrincipalRolesRequest,
            account_id: T.nilable(::String)
          )
            .void
        }
        def initialize(update_principal_roles_request:, account_id: nil)
          @update_principal_roles_request = update_principal_roles_request
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @update_principal_roles_request == other.update_principal_roles_request
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
