# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CloudinaryAccountProvisioning
  module Models
    module Operations

      class UpdateAccessKeyRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the product environment.
        field(
          :sub_account_id,
          ::String,
          {'path_param': {'field_name': "sub_account_id", 'style': "simple", 'explode': false}}
        )
        # The access key (api key).
        field :key, ::String, {'path_param': {'field_name': "key", 'style': "simple", 'explode': false}}
        # Access key details for update.
        field(
          :access_key_update_request,
          Models::Shared::AccessKeyUpdateRequest,
          {'request': {'media_type': "application/json"}}
        )
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig {
          params(
            sub_account_id: ::String,
            key: ::String,
            access_key_update_request: Models::Shared::AccessKeyUpdateRequest,
            account_id: T.nilable(::String)
          )
            .void
        }
        def initialize(sub_account_id:, key:, access_key_update_request:, account_id: nil)
          @sub_account_id = sub_account_id
          @key = key
          @access_key_update_request = access_key_update_request
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @sub_account_id == other.sub_account_id
          return false unless @key == other.key
          return false unless @access_key_update_request == other.access_key_update_request
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
