# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class CreateUserGroupRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # User group details.
        field :user_group_request, Models::Shared::UserGroupRequest, {'request': {'media_type': "application/json"}}
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig { params(user_group_request: Models::Shared::UserGroupRequest, account_id: T.nilable(::String)).void }
        def initialize(user_group_request:, account_id: nil)
          @user_group_request = user_group_request
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @user_group_request == other.user_group_request
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
