# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class GetAccessKeysRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the product environment.
        field(
          :sub_account_id,
          ::String,
          {'path_param': {'field_name': "sub_account_id", 'style': "simple", 'explode': false}}
        )
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # How many entries to display on each page.
        field(
          :page_size,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page_size", 'style': "form", 'explode': true}}
        )
        # Which page to return (maximum pages 100). **Default**: All pages are returned.
        #
        field(
          :page,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "page", 'style': "form", 'explode': true}}
        )
        # Which response parameter to sort by. **Possible values**: `api_key`, `created_at`, `name`, `enabled`.
        #
        field(
          :sort_by,
          Crystalline::Nilable.new(Models::Operations::SortBy),
          {'query_param': {'field_name': "sort_by", 'style': "form", 'explode': true}}
        )
        # Control the order of returned keys. **Possible values**: `desc` (default), `asc`.
        #
        field(
          :sort_order,
          Crystalline::Nilable.new(Models::Operations::SortOrder),
          {'query_param': {'field_name': "sort_order", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            sub_account_id: ::String,
            account_id: T.nilable(::String),
            page_size: T.nilable(::Integer),
            page: T.nilable(::Integer),
            sort_by: T.nilable(Models::Operations::SortBy),
            sort_order: T.nilable(Models::Operations::SortOrder)
          )
            .void
        }
        def initialize(sub_account_id:, account_id: nil, page_size: nil, page: nil, sort_by: nil, sort_order: nil)
          @sub_account_id = sub_account_id
          @account_id = account_id
          @page_size = page_size
          @page = page
          @sort_by = sort_by
          @sort_order = sort_order
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @sub_account_id == other.sub_account_id
          return false unless @account_id == other.account_id
          return false unless @page_size == other.page_size
          return false unless @page == other.page
          return false unless @sort_by == other.sort_by
          return false unless @sort_order == other.sort_order
          true
        end
      end
    end
  end
end
