# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 174bdf4189ac

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class GetBillingUsageRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # The year to retrieve billing usage for. Behavior depends on subscription type (see above).
        field(
          :year,
          Crystalline::Nilable.new(::Integer),
          {'query_param': {'field_name': "year", 'style': "form", 'explode': true}}
        )
        # Whether to include usage details by product environment. **Default**: false.
        #
        field(
          :include_prodenv_breakdown,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'query_param': {'field_name': "include_prodenv_breakdown", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            account_id: T.nilable(::String),
            year: T.nilable(::Integer),
            include_prodenv_breakdown: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(account_id: nil, year: nil, include_prodenv_breakdown: nil)
          @account_id = account_id
          @year = year
          @include_prodenv_breakdown = include_prodenv_breakdown
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @account_id == other.account_id
          return false unless @year == other.year
          return false unless @include_prodenv_breakdown == other.include_prodenv_breakdown
          true
        end
      end
    end
  end
end
