# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class GetProductEnvironmentsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # Whether to only return enabled product environments (true) or disabled product environments (false).
        # **Default**: all product environments are returned (both enabled and disabled).
        #
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'query_param': {'field_name': "enabled", 'style': "form", 'explode': true}}
        )
        # A list of up to 100 product environment IDs. When provided, other parameters are ignored.
        field(
          :ids,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'query_param': {'field_name': "ids", 'style': "form", 'explode': true}}
        )
        # A list of up to 100 product environment cloud names.
        field(
          :cloud_names,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'query_param': {'field_name': "cloud_names", 'style': "form", 'explode': true}}
        )
        # Returns product environments where the name begins with the specified case-insensitive string.
        field(
          :prefix,
          Crystalline::Nilable.new(::String),
          {'query_param': {'field_name': "prefix", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            account_id: T.nilable(::String),
            enabled: T.nilable(T::Boolean),
            ids: T.nilable(T::Array[::String]),
            cloud_names: T.nilable(T::Array[::String]),
            prefix: T.nilable(::String)
          )
            .void
        }
        def initialize(account_id: nil, enabled: nil, ids: nil, cloud_names: nil, prefix: nil)
          @account_id = account_id
          @enabled = enabled
          @ids = ids
          @cloud_names = cloud_names
          @prefix = prefix
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @account_id == other.account_id
          return false unless @enabled == other.enabled
          return false unless @ids == other.ids
          return false unless @cloud_names == other.cloud_names
          return false unless @prefix == other.prefix
          true
        end
      end
    end
  end
end
