# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 7e7edc34c4b8

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class GetRolesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Specifies whether to retrieve roles whose permissions apply globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
        field(
          :permission_type,
          Models::Shared::PermissionTypeEnum,
          {'query_param': {'field_name': "permission_type", 'style': "form", 'explode': true}}
        )
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # Specifies the level for retrieving policies or roles, either at the account level or within product environments.
        field(
          :scope_type,
          Crystalline::Nilable.new(Models::Shared::ScopeTypeEnum),
          {'query_param': {'field_name': "scope_type", 'style': "form", 'explode': true}}
        )
        # Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
        field(
          :management_type,
          Crystalline::Nilable.new(Models::Shared::ManagementTypeEnum),
          {'query_param': {'field_name': "management_type", 'style': "form", 'explode': true}}
        )
        # For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
        # - The content type can be: `folder_id` or `collection_id`.
        # - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
        #
        field(
          :policy_parameters,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'query_param': {'field_name': "policy_parameters", 'serialization': "json"}}
        )

        sig {
          params(
            permission_type: Models::Shared::PermissionTypeEnum,
            account_id: T.nilable(::String),
            scope_type: T.nilable(Models::Shared::ScopeTypeEnum),
            management_type: T.nilable(Models::Shared::ManagementTypeEnum),
            policy_parameters: T.nilable(T::Array[::String])
          )
            .void
        }
        def initialize(permission_type:, account_id: nil, scope_type: nil, management_type: nil, policy_parameters: nil)
          @permission_type = permission_type
          @account_id = account_id
          @scope_type = scope_type
          @management_type = management_type
          @policy_parameters = policy_parameters
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @permission_type == other.permission_type
          return false unless @account_id == other.account_id
          return false unless @scope_type == other.scope_type
          return false unless @management_type == other.management_type
          return false unless @policy_parameters == other.policy_parameters
          true
        end
      end
    end
  end
end
