# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 60a9cd274416

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class GetSystemPoliciesRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # Specifies whether to retrieve roles whose permissions apply globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
        field(
          :permission_type,
          Crystalline::Nilable.new(Models::Shared::PermissionTypeEnum),
          {'query_param': {'field_name': "permission_type", 'style': "form", 'explode': true}}
        )
        # Specifies the level for retrieving policies or roles, either at the account level or within product environments.
        field(
          :scope_type,
          Crystalline::Nilable.new(Models::Shared::ScopeTypeEnum),
          {'query_param': {'field_name': "scope_type", 'style': "form", 'explode': true}}
        )

        sig {
          params(
            account_id: T.nilable(::String),
            permission_type: T.nilable(Models::Shared::PermissionTypeEnum),
            scope_type: T.nilable(Models::Shared::ScopeTypeEnum)
          )
            .void
        }
        def initialize(account_id: nil, permission_type: nil, scope_type: nil)
          @account_id = account_id
          @permission_type = permission_type
          @scope_type = scope_type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @account_id == other.account_id
          return false unless @permission_type == other.permission_type
          return false unless @scope_type == other.scope_type
          true
        end
      end
    end
  end
end
