# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 76645a74cd9b

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class GetUserGroupsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )
        # Whether to only return extended (true) or basic information about the group (false).
        # **Default**: false.
        #
        field(
          :extended_details,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'query_param': {'field_name': "extended_details", 'style': "form", 'explode': true}}
        )

        sig { params(account_id: T.nilable(::String), extended_details: T.nilable(T::Boolean)).void }
        def initialize(account_id: nil, extended_details: nil)
          @account_id = account_id
          @extended_details = extended_details
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @account_id == other.account_id
          return false unless @extended_details == other.extended_details
          true
        end
      end
    end
  end
end
