# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: d14ea6d5e33c

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class InspectMultipleRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Role assignments for multiple principals.
        field :inspect_request, Models::Shared::InspectRequest, {'request': {'media_type': "application/json"}}
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig { params(inspect_request: Models::Shared::InspectRequest, account_id: T.nilable(::String)).void }
        def initialize(inspect_request:, account_id: nil)
          @inspect_request = inspect_request
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @inspect_request == other.inspect_request
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
