# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations
      # QueryParamSortBy
      class QueryParamSortBy < T::Enum
        enums do
          NAME = new("name")
          ROLE = new("role")
          STATUS = new("status")
          ACTIVITY = new("activity")
          CREATED_AT = new("created_at")
        end
      end
    end
  end
end
