# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: b183b38340e5

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations
      # QueryParamSortOrder - Control the order of returned users. **Possible values**: `desc` (default), `asc`.
      #
      class QueryParamSortOrder < T::Enum
        enums do
          DESC = new("desc")
          ASC = new("asc")
        end
      end
    end
  end
end
