# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations
      # UnionType - Whether to return users who last logged in within the specified date range (include) or those who didn't
      # last log in within the range (exclude). **Possible values**: `include`, `exclude`. **Default**: `include`.
      #
      class UnionType < T::Enum
        enums do
          INCLUDE = new("include")
          EXCLUDE = new("exclude")
        end
      end
    end
  end
end
