# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class UpdateRolePrincipalsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier for the role.
        field :role_id, ::String, {'path_param': {'field_name': "role_id", 'style': "simple", 'explode': false}}
        # Principals details.
        field(
          :update_role_principals_request,
          Models::Shared::UpdateRolePrincipalsRequest,
          {'request': {'media_type': "application/json"}}
        )
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig {
          params(
            role_id: ::String,
            update_role_principals_request: Models::Shared::UpdateRolePrincipalsRequest,
            account_id: T.nilable(::String)
          )
            .void
        }
        def initialize(role_id:, update_role_principals_request:, account_id: nil)
          @role_id = role_id
          @update_role_principals_request = update_role_principals_request
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @role_id == other.role_id
          return false unless @update_role_principals_request == other.update_role_principals_request
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
