# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 81402d8f2c62

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class UpdateUserGroupRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the user group.
        field :group_id, ::String, {'path_param': {'field_name': "group_id", 'style': "simple", 'explode': false}}
        # User group details to update.
        field :user_group_request, Models::Shared::UserGroupRequest, {'request': {'media_type': "application/json"}}
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig {
          params(
            group_id: ::String,
            user_group_request: Models::Shared::UserGroupRequest,
            account_id: T.nilable(::String)
          )
            .void
        }
        def initialize(group_id:, user_group_request:, account_id: nil)
          @group_id = group_id
          @user_group_request = user_group_request
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @group_id == other.group_id
          return false unless @user_group_request == other.user_group_request
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
