# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 21bf4115af49

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class UpdateRoleRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier for the role.
        field :role_id, ::String, {'path_param': {'field_name': "role_id", 'style': "simple", 'explode': false}}
        # Role details
        field :role, Models::Shared::Role, {'request': {'media_type': "application/json"}}
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig { params(role_id: ::String, role: Models::Shared::Role, account_id: T.nilable(::String)).void }
        def initialize(role_id:, role:, account_id: nil)
          @role_id = role_id
          @role = role
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @role_id == other.role_id
          return false unless @role == other.role
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
