# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: bde4006379cd

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Operations

      class UpdateCustomPolicyRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier for the custom permission policy.
        field :policy_id, ::String, {'path_param': {'field_name': "policy_id", 'style': "simple", 'explode': false}}
        # Policy details
        field :update_custom_policy, Models::Shared::UpdateCustomPolicy, {'request': {'media_type': "application/json"}}
        # Account ID
        field(
          :account_id,
          Crystalline::Nilable.new(::String),
          {'path_param': {'field_name': "account_id", 'style': "simple", 'explode': false}}
        )

        sig {
          params(
            policy_id: ::String,
            update_custom_policy: Models::Shared::UpdateCustomPolicy,
            account_id: T.nilable(::String)
          )
            .void
        }
        def initialize(policy_id:, update_custom_policy:, account_id: nil)
          @policy_id = policy_id
          @update_custom_policy = update_custom_policy
          @account_id = account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @policy_id == other.policy_id
          return false unless @update_custom_policy == other.update_custom_policy
          return false unless @account_id == other.account_id
          true
        end
      end
    end
  end
end
