# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 8903b3aa32d5

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module ServerVariables
      # ServerRegion - Regional endpoint selection
      class ServerRegion < T::Enum
        enums do
          API = new("api")
          API_EU = new("api-eu")
          API_AP = new("api-ap")
        end
      end
    end
  end
end
