# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 558b53521fa1

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Errors

      class PermissionsErrorResponse < StandardError
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :error,
          Crystalline::Nilable.new(Models::Shared::PermissionsError),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("error")}}
        )

        sig { params(error: T.nilable(Models::Shared::PermissionsError)).void }
        def initialize(error: nil)
          @error = error
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @error == other.error
          true
        end
      end
    end
  end
end
