# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: eca767cf937a

# typed: false
# frozen_string_literal: true

module Crystalline
  autoload :MetadataFields, 'crystalline/metadata_fields'
end


require_relative 'crystalline/utils'
require_relative 'crystalline/module'
require_relative 'crystalline/types'
