workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Cloudinary-Provisioning-OAS:
        inputs:
            - location: https://cloudinary.github.io/api-schemas/provisioning/schema.yml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: https://cloudinary.github.io/api-schemas/overlays/security-scheme-account-overlay.yaml
            - location: https://cloudinary.github.io/api-schemas/permissions/overlays/additional-properties-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/cloudinary/cloudinary/cloudinary-provisioning
targets:
    cloudinary:
        target: ruby
        source: Cloudinary-Provisioning-OAS
        publish:
            rubygems:
                token: $rubygems_auth_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cloudinary/cloudinary/cloudinary-provisioning-ruby-code-samples
            blocking: true
