# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 6144b4d9da76

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class AccessKeysResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # The list of the access keys.
        field(
          :access_keys,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::AccessKey)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("access_keys")}}
        )
        # Total number of the access keys.
        field(
          :total,
          Crystalline::Nilable.new(::Integer),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("total")}}
        )

        sig { params(access_keys: T.nilable(T::Array[Models::Shared::AccessKey]), total: T.nilable(::Integer)).void }
        def initialize(access_keys: nil, total: nil)
          @access_keys = access_keys
          @total = total
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @access_keys == other.access_keys
          return false unless @total == other.total
          true
        end
      end
    end
  end
end
