# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class AccessKeyRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the access key.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("name")}}
        )
        # Whether the access key is enabled or disabled.
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("enabled")}}
        )

        sig { params(name: T.nilable(::String), enabled: T.nilable(T::Boolean)).void }
        def initialize(name: nil, enabled: nil)
          @name = name
          @enabled = enabled
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @enabled == other.enabled
          true
        end
      end
    end
  end
end
