# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 3222cfea09da

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class AccessKeyUpdateRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the access key.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("name")}}
        )
        # Whether the access key is enabled or disabled.
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("enabled")}}
        )
        # Designates the access key for a specific purpose while allowing it to be used for other purposes, as well.
        # This action replaces any previously assigned key. **Possible values**: `webhooks`
        #
        field(
          :dedicated_for,
          Crystalline::Nilable.new(Models::Shared::DedicatedFor),
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("dedicated_for"),
              'decoder': ::CldProvisioning::Utils.enum_from_string(Models::Shared::DedicatedFor, true)
            }
          }
        )

        sig {
          params(
            name: T.nilable(::String),
            enabled: T.nilable(T::Boolean),
            dedicated_for: T.nilable(Models::Shared::DedicatedFor)
          )
            .void
        }
        def initialize(name: nil, enabled: nil, dedicated_for: nil)
          @name = name
          @enabled = enabled
          @dedicated_for = dedicated_for
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @enabled == other.enabled
          return false unless @dedicated_for == other.dedicated_for
          true
        end
      end
    end
  end
end
