# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 44578d246a97

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # Brief details of a single API Access Key.
      class ApiAccessKey
        extend T::Sig
        include Crystalline::MetadataFields

        # The API key.
        field(
          :key,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("key")}}
        )
        # The API secret.
        field(
          :secret,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("secret")}}
        )
        # Whether the access key is enabled or disabled.
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("enabled")}}
        )

        sig { params(key: T.nilable(::String), secret: T.nilable(::String), enabled: T.nilable(T::Boolean)).void }
        def initialize(key: nil, secret: nil, enabled: nil)
          @key = key
          @secret = secret
          @enabled = enabled
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @key == other.key
          return false unless @secret == other.secret
          return false unless @enabled == other.enabled
          true
        end
      end
    end
  end
end
