# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class CedarSchemaResponse
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :schema,
          Crystalline::Hash.new(Symbol, ::Object),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("schema"), required: true}}
        )

        sig { params(schema: T::Hash[Symbol, ::Object]).void }
        def initialize(schema:)
          @schema = schema
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @schema == other.schema
          true
        end
      end
    end
  end
end
