# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class CloudAssetTypeBreakdown
        extend T::Sig
        include Crystalline::MetadataFields

        # Storage usage for images in this product environment.
        field(
          :storage_image,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("storage_image")}}
        )
        # Storage usage for videos in this product environment.
        field(
          :storage_video,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("storage_video")}}
        )
        # Storage usage for raw files in this product environment.
        field(
          :storage_raw,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("storage_raw")}}
        )
        # Transformation usage for images in this product environment.
        field(
          :transformations_image,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("transformations_image")}}
        )
        # Transformation usage for videos in this product environment.
        field(
          :transformations_video,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("transformations_video")}}
        )
        # Bandwidth usage for images in this product environment.
        field(
          :bandwidth_image,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("bandwidth_image")}}
        )
        # Bandwidth usage for videos in this product environment.
        field(
          :bandwidth_video,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("bandwidth_video")}}
        )
        # Bandwidth usage for raw files in this product environment.
        field(
          :bandwidth_raw,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("bandwidth_raw")}}
        )
        # Number of times images were delivered (impressions) in this product environment.
        field(
          :image_impressions,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("image_impressions")}}
        )
        # Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio).
        field(
          :video_seconds,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("video_seconds")}}
        )
        # The name of the product environment.
        field(
          :cloud_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("cloud_name")}}
        )

        sig {
          params(
            storage_image: T.nilable(::Float),
            storage_video: T.nilable(::Float),
            storage_raw: T.nilable(::Float),
            transformations_image: T.nilable(::Float),
            transformations_video: T.nilable(::Float),
            bandwidth_image: T.nilable(::Float),
            bandwidth_video: T.nilable(::Float),
            bandwidth_raw: T.nilable(::Float),
            image_impressions: T.nilable(::Float),
            video_seconds: T.nilable(::Float),
            cloud_name: T.nilable(::String)
          )
            .void
        }
        def initialize(
          storage_image: nil,
          storage_video: nil,
          storage_raw: nil,
          transformations_image: nil,
          transformations_video: nil,
          bandwidth_image: nil,
          bandwidth_video: nil,
          bandwidth_raw: nil,
          image_impressions: nil,
          video_seconds: nil,
          cloud_name: nil
        )
          @storage_image = storage_image
          @storage_video = storage_video
          @storage_raw = storage_raw
          @transformations_image = transformations_image
          @transformations_video = transformations_video
          @bandwidth_image = bandwidth_image
          @bandwidth_video = bandwidth_video
          @bandwidth_raw = bandwidth_raw
          @image_impressions = image_impressions
          @video_seconds = video_seconds
          @cloud_name = cloud_name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @storage_image == other.storage_image
          return false unless @storage_video == other.storage_video
          return false unless @storage_raw == other.storage_raw
          return false unless @transformations_image == other.transformations_image
          return false unless @transformations_video == other.transformations_video
          return false unless @bandwidth_image == other.bandwidth_image
          return false unless @bandwidth_video == other.bandwidth_video
          return false unless @bandwidth_raw == other.bandwidth_raw
          return false unless @image_impressions == other.image_impressions
          return false unless @video_seconds == other.video_seconds
          return false unless @cloud_name == other.cloud_name
          true
        end
      end
    end
  end
end
