# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class CustomPoliciesResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # An array of custom policies.
        field(
          :data,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::CustomPolicyResponseData)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("data")}}
        )
        # When a request has more results to return, the next_cursor value is returned as part of the response. You can then specify this value as the cursor parameter of a following request.
        field(
          :next_cursor,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("next_cursor")}}
        )

        sig {
          params(data: T.nilable(T::Array[Models::Shared::CustomPolicyResponseData]), next_cursor: T.nilable(::String))
            .void
        }
        def initialize(data: nil, next_cursor: nil)
          @data = data
          @next_cursor = next_cursor
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @data == other.data
          return false unless @next_cursor == other.next_cursor
          true
        end
      end
    end
  end
end
