# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class Cycles
        extend T::Sig
        include Crystalline::MetadataFields

        # The start date of the billing cycle.
        field(
          :from_day,
          Crystalline::Nilable.new(::Date),
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("from_day"),
              'decoder': ::CldProvisioning::Utils.date_from_iso_format(true)
            }
          }
        )
        # The end date of the billing cycle.
        field(
          :to_day,
          Crystalline::Nilable.new(::Date),
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("to_day"),
              'decoder': ::CldProvisioning::Utils.date_from_iso_format(true)
            }
          }
        )
        # Total usage for this cycle.
        field(
          :usage,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("usage")}}
        )
        # Usage breakdown by asset type and operation.
        field(
          :breakdown,
          Crystalline::Nilable.new(Models::Shared::Breakdown),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("breakdown")}}
        )
        # Optional breakdown by product environment. May not be present in all responses.
        field(
          :product_environment_breakdown,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::CloudAssetTypeBreakdown)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("product_environment_breakdown")}}
        )

        sig {
          params(
            from_day: T.nilable(::Date),
            to_day: T.nilable(::Date),
            usage: T.nilable(::Float),
            breakdown: T.nilable(Models::Shared::Breakdown),
            product_environment_breakdown: T.nilable(T::Array[Models::Shared::CloudAssetTypeBreakdown])
          )
            .void
        }
        def initialize(from_day: nil, to_day: nil, usage: nil, breakdown: nil, product_environment_breakdown: nil)
          @from_day = from_day
          @to_day = to_day
          @usage = usage
          @breakdown = breakdown
          @product_environment_breakdown = product_environment_breakdown
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @from_day == other.from_day
          return false unless @to_day == other.to_day
          return false unless @usage == other.usage
          return false unless @breakdown == other.breakdown
          return false unless @product_environment_breakdown == other.product_environment_breakdown
          true
        end
      end
    end
  end
end
