# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # DedicatedFor - Designates the access key for a specific purpose while allowing it to be used for other purposes, as well.
      # This action replaces any previously assigned key. **Possible values**: `webhooks`
      #
      class DedicatedFor < T::Enum
        enums do
          WEBHOOKS = new("webhooks")
        end
      end
    end
  end
end
