# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 690235b51f71

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class EffectivePolicy
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the permission policy.
        field(
          :id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("id")}}
        )
        # A Cedar statement that permits or forbids a principal to perform an action on a resource. Refer to the [Permissions API guide](permissions_api_guide) for more information.
        field(
          :policy_statement,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("policy_statement")}}
        )

        sig { params(id: T.nilable(::String), policy_statement: T.nilable(::String)).void }
        def initialize(id: nil, policy_statement: nil)
          @id = id
          @policy_statement = policy_statement
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @policy_statement == other.policy_statement
          true
        end
      end
    end
  end
end
