# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 074bdeccd79c

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # The user's email preferences.
      class EmailPreferences
        extend T::Sig
        include Crystalline::MetadataFields

        def initialize
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          true
        end
      end
    end
  end
end
