# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: a8cfad806719

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class Error
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :message,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("message")}}
        )

        sig { params(message: T.nilable(::String)).void }
        def initialize(message: nil)
          @message = message
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @message == other.message
          true
        end
      end
    end
  end
end
