# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: b160fe795e7d

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class InspectRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Specifies where the role/policy is applied, either at the account level or within product environments.
        field(
          :scope_type,
          Models::Shared::ScopeTypeEnum,
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("scope_type"),
              required: true,
              'decoder': ::CldProvisioning::Utils.open_enum_from_string(Models::Shared::ScopeTypeEnum, false)
            }
          }
        )

        field(
          :principals,
          Crystalline::Array.new(Models::Shared::Principal),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("principals"), required: true}}
        )

        field(
          :scope_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("scope_id")}}
        )

        field(
          :policy_parameters,
          Crystalline::Nilable.new(Models::Shared::InspectRequestPolicyParameters),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("policy_parameters")}}
        )

        field(
          :cursor,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("cursor")}}
        )

        sig {
          params(
            scope_type: Models::Shared::ScopeTypeEnum,
            principals: T::Array[Models::Shared::Principal],
            scope_id: T.nilable(::String),
            policy_parameters: T.nilable(Models::Shared::InspectRequestPolicyParameters),
            cursor: T.nilable(::String)
          )
            .void
        }
        def initialize(scope_type:, principals:, scope_id: nil, policy_parameters: nil, cursor: nil)
          @scope_type = scope_type
          @principals = principals
          @scope_id = scope_id
          @policy_parameters = policy_parameters
          @cursor = cursor
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @scope_type == other.scope_type
          return false unless @principals == other.principals
          return false unless @scope_id == other.scope_id
          return false unless @policy_parameters == other.policy_parameters
          return false unless @cursor == other.cursor
          true
        end
      end
    end
  end
end
