# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # ManagementTypeEnum - Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
      class ManagementTypeEnum
        include ::Crystalline::Enum
        enums do
          SYSTEM = new("system")
          CUSTOM = new("custom")
        end

        open!
      end
    end
  end
end
