# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: a003e1259e16

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class MetricUsage
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of metric being measured (e.g., "credit").
        field(
          :metric,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("metric")}}
        )
        # The limit for this metric in the plan.
        field(
          :limit,
          Crystalline::Nilable.new(::Float),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("limit")}}
        )
        # Full usage details per billing cycle (monthly or annual, depending on plan).
        field(
          :cycles,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::Cycles)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("cycles")}}
        )
        # Monthly-level breakdown within a single annual cycle.
        field(
          :monthly_cycles,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::MonthlyCycles)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("monthly_cycles")}}
        )

        sig {
          params(
            metric: T.nilable(::String),
            limit: T.nilable(::Float),
            cycles: T.nilable(T::Array[Models::Shared::Cycles]),
            monthly_cycles: T.nilable(T::Array[Models::Shared::MonthlyCycles])
          )
            .void
        }
        def initialize(metric: nil, limit: nil, cycles: nil, monthly_cycles: nil)
          @metric = metric
          @limit = limit
          @cycles = cycles
          @monthly_cycles = monthly_cycles
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @metric == other.metric
          return false unless @limit == other.limit
          return false unless @cycles == other.cycles
          return false unless @monthly_cycles == other.monthly_cycles
          true
        end
      end
    end
  end
end
