# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: c0167bd2048c

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # OperationEnum - Specifies the operation to perform. Use `add` to associate or `remove` to disassociate.
      class OperationEnum < T::Enum
        enums do
          ADD = new("add")
          REMOVE = new("remove")
        end
      end
    end
  end
end
