# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: bca35f998b8d

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class PermissionsError
        extend T::Sig
        include Crystalline::MetadataFields

        # A classification of the error, indicating the general area or type of problem.
        field(
          :category,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("category")}}
        )
        # A specific error code that uniquely identifies the error condition.
        field(
          :code,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("code")}}
        )
        # A human-readable message providing a brief explanation of the error and its cause.
        field(
          :message,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("message")}}
        )
        # Additional contextual information about the error, which may include relevant data.
        field(
          :details,
          Crystalline::Nilable.new(Models::Shared::Details),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("details")}}
        )

        sig {
          params(
            category: T.nilable(::String),
            code: T.nilable(::String),
            message: T.nilable(::String),
            details: T.nilable(Models::Shared::Details)
          )
            .void
        }
        def initialize(category: nil, code: nil, message: nil, details: nil)
          @category = category
          @code = code
          @message = message
          @details = details
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @category == other.category
          return false unless @code == other.code
          return false unless @message == other.message
          return false unless @details == other.details
          true
        end
      end
    end
  end
end
