# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 237f815c3f41

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class PrincipalRolesInspectResponseData
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :principals,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::PrincipalRolesInspectData)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("principals")}}
        )

        sig { params(principals: T.nilable(T::Array[Models::Shared::PrincipalRolesInspectData])).void }
        def initialize(principals: nil)
          @principals = principals
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @principals == other.principals
          true
        end
      end
    end
  end
end
