# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 82d1569cc434

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class PrincipalRole
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of principal you want to retrieve roles or permission policies for.
        #
        # - user
        #
        # - group
        #
        # - apiKey
        #
        # - provisioningKey
        #
        field(
          :principal_type,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("principal_type")}}
        )
        # The unique identifier of the principal.
        field(
          :principal_id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("principal_id")}}
        )
        # A list of all the roles that are added to this principal.
        field(
          :roles,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::EffectiveRole)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("roles")}}
        )

        sig {
          params(
            principal_type: T.nilable(::String),
            principal_id: T.nilable(::String),
            roles: T.nilable(T::Array[Models::Shared::EffectiveRole])
          )
            .void
        }
        def initialize(principal_type: nil, principal_id: nil, roles: nil)
          @principal_type = principal_type
          @principal_id = principal_id
          @roles = roles
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @principal_type == other.principal_type
          return false unless @principal_id == other.principal_id
          return false unless @roles == other.roles
          true
        end
      end
    end
  end
end
