# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class Principal
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of principal.
        field(
          :type,
          Models::Shared::PrincipalTypeEnum,
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("type"),
              required: true,
              'decoder': ::CldProvisioning::Utils.open_enum_from_string(Models::Shared::PrincipalTypeEnum, false)
            }
          }
        )
        # The unique identifier of the principal.
        field :id, ::String, {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("id"), required: true}}

        sig { params(type: Models::Shared::PrincipalTypeEnum, id: ::String).void }
        def initialize(type:, id:)
          @type = type
          @id = id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @type == other.type
          return false unless @id == other.id
          true
        end
      end
    end
  end
end
