# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: fbaaf00e69fc

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class PrincipalRolesInspectData
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of principal.
        field(
          :type,
          Models::Shared::PrincipalTypeEnum,
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("type"),
              required: true,
              'decoder': ::CldProvisioning::Utils.open_enum_from_string(Models::Shared::PrincipalTypeEnum, false)
            }
          }
        )
        # The unique identifier of the principal.
        field :id, ::String, {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("id"), required: true}}

        field(
          :roles,
          Crystalline::Array.new(Models::Shared::PrincipalRolesData),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("roles"), required: true}}
        )

        sig {
          params(
            type: Models::Shared::PrincipalTypeEnum,
            id: ::String,
            roles: T::Array[Models::Shared::PrincipalRolesData]
          )
            .void
        }
        def initialize(type:, id:, roles:)
          @type = type
          @id = id
          @roles = roles
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @type == other.type
          return false unless @id == other.id
          return false unless @roles == other.roles
          true
        end
      end
    end
  end
end
