# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 99814ef5dc11

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # PrincipalTypeEnum - The type of principal.
      class PrincipalTypeEnum
        include ::Crystalline::Enum
        enums do
          USER = new("user")
          GROUP = new("group")
          API_KEY = new("apiKey")
          PROVISIONING_KEY = new("provisioningKey")
        end

        open!
      end
    end
  end
end
