# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 8910f6b8137f

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class ProductEnvironmentsResponse
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :sub_accounts,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::ProductEnvironment)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("sub_accounts")}}
        )

        sig { params(sub_accounts: T.nilable(T::Array[Models::Shared::ProductEnvironment])).void }
        def initialize(sub_accounts: nil)
          @sub_accounts = sub_accounts
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @sub_accounts == other.sub_accounts
          true
        end
      end
    end
  end
end
