# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 3b5a1cdea65b

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # Product Environment
      class ProductEnvironment
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :cloud_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("cloud_name")}}
        )
        # The cloud name of the product environment.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("name")}}
        )
        # Whether the product environment is enabled or disabled.
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("enabled")}}
        )
        # The ID of the product environment.
        field(
          :id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("id")}}
        )
        # The list of the product environment's access keys.
        field(
          :api_access_keys,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::ApiAccessKey)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("api_access_keys")}}
        )
        # The date when the product environment was created.
        field(
          :created_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("created_at"),
              'decoder': ::CldProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # The date when the product environment was last updated.
        field(
          :updated_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("updated_at"),
              'decoder': ::CldProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )

        sig {
          params(
            cloud_name: T.nilable(::String),
            name: T.nilable(::String),
            enabled: T.nilable(T::Boolean),
            id: T.nilable(::String),
            api_access_keys: T.nilable(T::Array[Models::Shared::ApiAccessKey]),
            created_at: T.nilable(::DateTime),
            updated_at: T.nilable(::DateTime)
          )
            .void
        }
        def initialize(
          cloud_name: nil,
          name: nil,
          enabled: nil,
          id: nil,
          api_access_keys: nil,
          created_at: nil,
          updated_at: nil
        )
          @cloud_name = cloud_name
          @name = name
          @enabled = enabled
          @id = id
          @api_access_keys = api_access_keys
          @created_at = created_at
          @updated_at = updated_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @cloud_name == other.cloud_name
          return false unless @name == other.name
          return false unless @enabled == other.enabled
          return false unless @id == other.id
          return false unless @api_access_keys == other.api_access_keys
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
