# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: a9366f134a66

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class ProductEnvironmentUpdateRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The display name for the product environment.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("name")}}
        )
        # The Cloudinary cloud name. An error is returned if the requested name already exists.
        # **Note**: Can only be changed for accounts with fewer than 1000 images.
        #
        field(
          :cloud_name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("cloud_name")}}
        )
        # Custom attributes associated with the product environment.
        field(
          :custom_attributes,
          Crystalline::Nilable.new(Models::Shared::ProductEnvironmentUpdateRequestCustomAttributes),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("custom_attributes")}}
        )
        # Whether the product environment is enabled. **Default**: true.
        #
        field(
          :enabled,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("enabled")}}
        )

        sig {
          params(
            name: T.nilable(::String),
            cloud_name: T.nilable(::String),
            custom_attributes: T.nilable(Models::Shared::ProductEnvironmentUpdateRequestCustomAttributes),
            enabled: T.nilable(T::Boolean)
          )
            .void
        }
        def initialize(name: nil, cloud_name: nil, custom_attributes: nil, enabled: nil)
          @name = name
          @cloud_name = cloud_name
          @custom_attributes = custom_attributes
          @enabled = enabled
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @cloud_name == other.cloud_name
          return false unless @custom_attributes == other.custom_attributes
          return false unless @enabled == other.enabled
          true
        end
      end
    end
  end
end
