# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class RolesResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # An array of roles.
        field(
          :data,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::RoleResponseData)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("data")}}
        )

        sig { params(data: T.nilable(T::Array[Models::Shared::RoleResponseData])).void }
        def initialize(data: nil)
          @data = data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @data == other.data
          true
        end
      end
    end
  end
end
