# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # ScopeTypeEnum - Specifies where the role/policy is applied, either at the account level or within product environments.
      class ScopeTypeEnum
        include ::Crystalline::Enum
        enums do
          ACCOUNT = new("account")
          PRODENV = new("prodenv")
        end

        open!
      end
    end
  end
end
