# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 2b81ec2d4ef7

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class SystemRolesAndPoliciesCatalogResponse
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :catalog,
          Crystalline::Hash.new(Symbol, ::Object),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("catalog"), required: true}}
        )

        sig { params(catalog: T::Hash[Symbol, ::Object]).void }
        def initialize(catalog:)
          @catalog = catalog
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @catalog == other.catalog
          true
        end
      end
    end
  end
end
