# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class SystemPolicyResponseData
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the policy.
        field :id, ::String, {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("id"), required: true}}
        # The name of the policy
        field(
          :name,
          ::String,
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("name"), required: true}}
        )
        # Specifies where the role/policy is applied, either at the account level or within product environments.
        field(
          :scope_type,
          Models::Shared::ScopeTypeEnum,
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("scope_type"),
              required: true,
              'decoder': ::CldProvisioning::Utils.open_enum_from_string(Models::Shared::ScopeTypeEnum, false)
            }
          }
        )
        # A Cedar policy that permits or forbids a certain action on a certain element to a principal (user, group, or API key).
        field(
          :policy_statement,
          ::String,
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("policy_statement"), required: true}}
        )
        # Creation time of the policy in epoch time.
        field(
          :created_at,
          ::Integer,
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("created_at"), required: true}}
        )
        # Last update time of the policy in epoch time.
        field(
          :updated_at,
          ::Integer,
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("updated_at"), required: true}}
        )
        # Specifies whether the permission applies globally across all resources or contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
        #
        #     - global
        #
        #     - content
        #
        field(
          :permission_type,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("permission_type")}}
        )
        # For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
        # - The content type can be: `folder_id` or `collection_id`.
        # - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
        #
        field(
          :policy_parameters,
          Crystalline::Nilable.new(Crystalline::Array.new(::String)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("policy_parameters")}}
        )
        # The category of the policy.
        field(
          :category,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("category")}}
        )
        # The sub-category of the policy.
        field(
          :sub_category,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("sub_category")}}
        )
        # A short description of the policy.
        field(
          :description,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("description")}}
        )

        sig {
          params(
            id: ::String,
            name: ::String,
            scope_type: Models::Shared::ScopeTypeEnum,
            policy_statement: ::String,
            created_at: ::Integer,
            updated_at: ::Integer,
            permission_type: T.nilable(::String),
            policy_parameters: T.nilable(T::Array[::String]),
            category: T.nilable(::String),
            sub_category: T.nilable(::String),
            description: T.nilable(::String)
          )
            .void
        }
        def initialize(
          id:,
          name:,
          scope_type:,
          policy_statement:,
          created_at:,
          updated_at:,
          permission_type: nil,
          policy_parameters: nil,
          category: nil,
          sub_category: nil,
          description: nil
        )
          @id = id
          @name = name
          @scope_type = scope_type
          @policy_statement = policy_statement
          @created_at = created_at
          @updated_at = updated_at
          @permission_type = permission_type
          @policy_parameters = policy_parameters
          @category = category
          @sub_category = sub_category
          @description = description
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @scope_type == other.scope_type
          return false unless @policy_statement == other.policy_statement
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          return false unless @permission_type == other.permission_type
          return false unless @policy_parameters == other.policy_parameters
          return false unless @category == other.category
          return false unless @sub_category == other.sub_category
          return false unless @description == other.description
          true
        end
      end
    end
  end
end
