# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class UserGroupRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The user group's name.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("name")}}
        )
        # Whether to only return extended (true) or basic information about the group (false).
        # **Default**: false.
        #
        field(
          :extended_details,
          Crystalline::Nilable.new(Crystalline::Boolean.new),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("extended_details")}}
        )

        sig { params(name: T.nilable(::String), extended_details: T.nilable(T::Boolean)).void }
        def initialize(name: nil, extended_details: nil)
          @name = name
          @extended_details = extended_details
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @name == other.name
          return false unless @extended_details == other.extended_details
          true
        end
      end
    end
  end
end
