# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 5f065734234f

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # UserRequestRole - The role to assign.
      class UserRequestRole < T::Enum
        enums do
          MASTER_ADMIN = new("master_admin")
          ADMIN = new("admin")
          BILLING = new("billing")
          TECHNICAL_ADMIN = new("technical_admin")
          REPORTS = new("reports")
          MEDIA_LIBRARY_ADMIN = new("media_library_admin")
          MEDIA_LIBRARY_USER = new("media_library_user")
        end
      end
    end
  end
end
