# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 2726f5a5ff0f

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared
      # User group.
      class UserGroup
        extend T::Sig
        include Crystalline::MetadataFields

        # The user group's ID.
        field(
          :id,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("id")}}
        )
        # The user group's name.
        field(
          :name,
          Crystalline::Nilable.new(::String),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("name")}}
        )
        # A list of user group users.
        # Only returned in extended_details.
        #
        field(
          :users,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::UserGroupUser)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("users")}}
        )
        # The date when the user group was created.
        # Only returned in extended_details.
        #
        field(
          :created_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("created_at"),
              'decoder': ::CldProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )
        # The date when the user group was last updated.
        # Only returned in extended_details.
        #
        field(
          :updated_at,
          Crystalline::Nilable.new(::DateTime),
          {
            'format_json': {
              'letter_case': ::CldProvisioning::Utils.field_name("updated_at"),
              'decoder': ::CldProvisioning::Utils.datetime_from_iso_format(true)
            }
          }
        )

        sig {
          params(
            id: T.nilable(::String),
            name: T.nilable(::String),
            users: T.nilable(T::Array[Models::Shared::UserGroupUser]),
            created_at: T.nilable(::DateTime),
            updated_at: T.nilable(::DateTime)
          )
            .void
        }
        def initialize(id: nil, name: nil, users: nil, created_at: nil, updated_at: nil)
          @id = id
          @name = name
          @users = users
          @created_at = created_at
          @updated_at = updated_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @users == other.users
          return false unless @created_at == other.created_at
          return false unless @updated_at == other.updated_at
          true
        end
      end
    end
  end
end
