# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 8a955af44150

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class UserGroupsListResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # A list of user groups that the user belongs to.
        field(
          :groups,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::UserGroupSummary)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("groups")}}
        )

        sig { params(groups: T.nilable(T::Array[Models::Shared::UserGroupSummary])).void }
        def initialize(groups: nil)
          @groups = groups
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @groups == other.groups
          true
        end
      end
    end
  end
end
