# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: 5a514a5fbd7e

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class ValidateCedarPolicyRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The Cedar policy statement to validate.
        field(
          :policy,
          ::String,
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("policy"), required: true}}
        )

        sig { params(policy: ::String).void }
        def initialize(policy:)
          @policy = policy
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @policy == other.policy
          true
        end
      end
    end
  end
end
