# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# @generated-id: a03732fe1e88

# typed: true
# frozen_string_literal: true

module CldProvisioning
  module Models
    module Shared

      class ValidateCedarPolicyResponse
        extend T::Sig
        include Crystalline::MetadataFields

        field(
          :valid,
          Crystalline::Boolean.new,
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("valid"), required: true}}
        )

        field(
          :errors,
          Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::CedarError)),
          {'format_json': {'letter_case': ::CldProvisioning::Utils.field_name("errors")}}
        )

        sig { params(valid: T::Boolean, errors: T.nilable(T::Array[Models::Shared::CedarError])).void }
        def initialize(valid:, errors: nil)
          @valid = valid
          @errors = errors
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a?(self.class)
          return false unless @valid == other.valid
          return false unless @errors == other.errors
          true
        end
      end
    end
  end
end
